### ISSUE TITLE
Address zero violation for Naturist class

### ISSUE THREAD

**Issue by caligari87** [MatthewTheGlutton/HideousDestructor#1]
Running on GZDoom 3.1.0 with the latest code from commit bf8d470, and selecting the Naturist class gives a soft crash with this error:

```
VM execution aborted: tried to read from address zero.
Called from HDPlayerPawn.Tick at :zscript/player.txt, line 182
```

Looks like that line is checking for a ready weapon, but obviously the class has none.

**Comment by MatthewTheGlutton** [comment]
Fixed. https://github.com/MatthewTheGlutton/HideousDestructor/commit/398900966e6863cc9e294f220ab6cfa5803add42#diff-e0d5608a5281f974f236d540bf9a2961L181
