### ISSUE TITLE
7.76 reload between levels not working

### ISSUE THREAD

**Issue by Derpford** [MatthewTheGlutton/HideousDestructor#10]
I'm not sure if this happened because of the mag update, but it appears that--despite collecting all my brass ~~like a good little soldier~~ and unloading all my half-empty ZM66 mags, I'm not getting the between-level reloaded 7.76 rounds. Since I chose "Classic Rifleman", I *do* have a Liberator, so I should be getting the reloading...right?

EDIT: This was in Release 3.3.2.6.

**Comment by Derpford** [comment]
Update: None of the between-level things are running. This is insanely weird.

Loaded pk3s:
Hideous Destructor 3.3.2.6
hd_snd_1.4_ogg
darkdoomz_v1.1
steve_flashlight_2018.02.12
droplets_v15_hd
Tilt++
autoautosave-0.10.3
Darken2

**Comment by MatthewTheGlutton** [comment]
can you try loading one mod at a time until it stops working?

**Comment by MatthewTheGlutton** [comment]
no one else has reported this one or similar either

**Comment by Derpford** [comment]
I've got it! I did some testing finally, with v3.5.0, and I've narrowed down what causes both this and #11. For some reason, Tilt++ causes end-of-level logic to not happen.

**Comment by MatthewTheGlutton** [comment]
Just tried Tilt++ v1.5, works without a hitch. o_O

You weren't loading anything else, right?

**Comment by Derpford** [comment]
I was loading other things, but individual testing revealed it was Tilt++...

...specifically, an older version. Loading v1.5 fixed it, and now everything works as intended. This and #11 can be closed now.
