### ISSUE TITLE
Make the Slayer backpackable

### ISSUE THREAD

**Issue by boogiebogus** [MatthewTheGlutton/HideousDestructor#100]
![image](https://user-images.githubusercontent.com/53976699/74881685-c1ee0980-533b-11ea-824d-c48bdad19b7d.png)
![image](https://user-images.githubusercontent.com/53976699/74882253-c36c0180-533c-11ea-9d68-be68a565c5fe.png)

As can be seen in the image, the slayer is the very length as the bullpup liberator, which fits in a backpack. It would probably be around an inch or so longer, so it should probably fit.

**Comment by MatthewTheGlutton** [comment]
Addressed in d5b812b55724b35060fb99e5b2f60fa2f37f43f7
