### ISSUE TITLE
Can't throw more DERPs if one is sticked to a wall.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#102]
1. Go to range.
2. Give yourself 2+ DERPs.
3. Stick one on the wall with `derp 555`.
4. You won't see the inventory item for the other DERPs, so you can't throw them.

**Comment by MatthewTheGlutton** [comment]
I think it's fixed but there are way too many moving parts...

**Comment by Accensus** [comment]
Just tested. Looks fixed from what I can see. Will post more if anything pops up. Thanks!
