### ISSUE TITLE
Make DERP and HERP controllers not be affected by crosshair size.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#103]
I'm playing on the smallest crosshair setting, and while I can live with the scope for everything else being small (I kinda chose this, didn't I?), the scope for the HERP/DERP feels comically small.

Alternatively, an option to decouple sights scaling from the scopes. That would actually be the best solution. I mainly play on this setting because I feel that the feedback is much more immediate.

**Comment by MatthewTheGlutton** [comment]
I just checked the code for this. The scale is factored in very early in the process, to avoid having to juggle way too many moving parts in each crosshair function, so there's no simple, sane way to make the parts scale independently of each other now.

Let's just file this under "maybe next time I do a massive overhaul of the crosshair/sightpicture system"...
