### ISSUE TITLE
Prevent accidental usage of incap items.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#104]
Title may be misleading but I can't put the whole thing in there. Here's the situation:
Often times when I get incapped if I press/hold alt-fire it fumbles for items instead of doing nothing. This has lead to accidentally fumbling and using my only berserk kit when I've wanted to save it for emergency situations. This does not always happen and I cannot pinpoint when it does.

**Comment by MatthewTheGlutton** [comment]
I believe the same fix should address this that deals with #105

**Comment by Accensus** [comment]
Doesn't seem to be fixed.

**Comment by Accensus** [comment]
Actually nevermind. It is fixed. It only fumbles for items the second time I press alt-fire, as it's supposed to. My bad.
