### ISSUE TITLE
Prevent stripping with Reload while incapped.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#105]
Can't count the times I've been incapped while doing distracting punches while zerked and accidentally stripped my armor as I hit the ground. I likely could have survived most of those situations if I still had my armor on.

**Comment by boogiebogus** [comment]
then your teammate can't staple you back together in multi...

**Comment by Accensus** [comment]
hd_strip won't work? Or is Reload just a shortcut for hd_strip?

**Comment by MatthewTheGlutton** [comment]
It is intentional but I can see how this can screw up unintentionally.

I've added a time delay in the incap interface's select, where if you keep holding a button you will go to the "nope" state and things would continue to fail to repond until you let go.
