### ISSUE TITLE
HERP gives false empty cartridge warnings.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#106]
Can't reproduce reliably. Sometimes it happens, sometimes it doesn't. Might be intentional.

**Comment by MatthewTheGlutton** [comment]
Are there any dirty mags loaded?

**Comment by Accensus** [comment]
I think there were 1-2, yeah.

**Comment by MatthewTheGlutton** [comment]
That's probably it. It does sometimes randomly fail, the idea being it should abort where the ZM would jam or the Vulc is able to just chew right through the round.
