### ISSUE TITLE
Cycle same stack switches to fist.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#108]
It didn't do that half an hour ago. I have zero clue what happened or why or how.

EDIT: Gotta start a new game to fix it and I'm already 11 maps in. Need to drop weapons and stuff to do inventory management. Guess I'll take a break for now until it's fixed.

**Comment by MatthewTheGlutton** [comment]
Is this from a save game from before an update?

**Comment by Accensus** [comment]
It started happening after the recent updates, if that's what you're asking. Gonna revert and see if it persists.

**Comment by MatthewTheGlutton** [comment]
I mean, did you
1. play HD under one version
2. save that game
3. update HD
4. load that previously saved game with the updated HD

**Comment by Accensus** [comment]
Ah, yes.

**Comment by Accensus** [comment]
The thing is that it didn't do it immediately after updating. It just started doing it out of the blue from what I recall.

**Comment by MatthewTheGlutton** [comment]
Are you able to switch back to the weapon from the fist, or is it as though the weapon never existed?

**Comment by Accensus** [comment]
I can switch back to it, no problem. I'm noticing that the normal behaviour when cycling is `Lower weapon -> switch to fist -> switch to next weapon in stack`, but right now that last step is skipped.

**Comment by MatthewTheGlutton** [comment]
Are all weapons affected or just some? It does switch to fist as a fallback but that switch should always be called before the switch to the swapped-in weapon and thus overridden... except that the fist always happens after 1 tic and the swapped-in happens after 4 tics or a formula based on mass, whichever is greater, so that should never happen in the wrong order either.

So this never happens right away, right? Seems like some thinker or something is not being cleared...

**Comment by Accensus** [comment]
> Are all weapons affected or just some?
Pretty much everything. Liberator, SMG, even HERPs, you name it. It happens even if you don't have a second weapon to switch to.

>So this never happens right away, right?
I think so.

**Comment by MatthewTheGlutton** [comment]
After looking at the switch code I think I see one way that you could end up with the fist taking preeminence.

This latest commit might address it.

**Comment by Accensus** [comment]
Well, that didn't fix the save game, but it might prevent this from happening in the future. This is one of those bugs that's hard to test.

**Comment by MatthewTheGlutton** [comment]
Seeing as we're not going to be able to replicate this from startup anytime soon I'll close this for now.
