### ISSUE TITLE
Suggestion: Key-combination for unloading battery on Vulcanette

### ISSUE THREAD

**Issue by physixcat** [MatthewTheGlutton/HideousDestructor#109]
I'd like to suggest adding a key combo to remove a battery from a Vulcanette without having to first unload all its ammo. This would significantly accelerate the process of scavenging them from dead chaingunners

**Comment by caligari87** [comment]
maybe `AltReload` ejects a loaded battery, or loads a new one if there is none inserted. Basically split the "reload" into two stages instead of one.

**Comment by Accensus** [comment]
Use + Alt. Reload is probably a good and intuitive combo.

**Comment by MatthewTheGlutton** [comment]
In principle I know how to do this but I haven't tested this change, can you guys confirm that it (and the added use-key help text) work?

**Comment by Accensus** [comment]
> EDIT: wait, Use+Altreload not Use+Unload? uhhhh.....

I guess that also works, but I find Use + Alt. Reload more intuitive.

>EDIT2: According to the HERP code Use+Unload should also work to unload the battery???

It does, but it unloads mags first.

**Comment by MatthewTheGlutton** [comment]
Both added, yet untested because too much stuff open on toaster

**Comment by Accensus** [comment]
Works just fine, though Use + Alt. Reload doesn't show up on the help screen. Probably intentional.

**Comment by MatthewTheGlutton** [comment]
Was not, added now.

**Comment by Accensus** [comment]
Very bueno. Thanks!
