### ISSUE TITLE
DERP commands not working?

### ISSUE THREAD

**Issue by Derpford** [MatthewTheGlutton/HideousDestructor#11]
So, I've been trying to use the DERP's remote-switch capability, and it isn't working. And, in fact, none of the DERP commands appear to be working properly. I don't get any of the text feedback that I used to when using derp commands, and "derptag" does not set the DERP's tag.

**Comment by MatthewTheGlutton** [comment]
works for me

version of gzdoom?
wads loaded?
map?

**Comment by MatthewTheGlutton** [comment]
no one else has reported issues so i'm closing this
