### ISSUE TITLE
Drop item drops the selected armor last.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#111]
If I have two armors with, say, 29 and 55 durability left, and have selected the 55 one, pressing "drop item" would drop the one with 29 first.

**Comment by MatthewTheGlutton** [comment]
That took a surprisingly long time to do.

Selected armour is now last in the array, just like mags and the mag manager.

**Comment by MatthewTheGlutton** [comment]
Left this open as a reminder to myself to update my draft changelog, closing now.
