### ISSUE TITLE
playing with any non-strictly compatible pk3 or wad breaks loadouts

### ISSUE THREAD

**Issue by fr1kker** [MatthewTheGlutton/HideousDestructor#114]
Trying to play with a WadSmoosh wad (consisting of Doom 1 + 2, Master Levels, and Final Doom). Whenever I add the .pk3 or .wad and run it, the game itself works fine but all of the loadouts say "LOADOUT __", "because showing up is half the battle." This doesn't just happen with wads, either. It's happened with Nash's Gore Mod, so I assume there's an error with non strictly compatible files. However, Ugly As Sin works.

**Comment by boogiebogus** [comment]
if i remember correctly, loadouts are saved as CVars, so there's probably something wrong with your GZDoom rather than it being caused by HD. Do you get the same results with a fresh install of gzdoom?

**Comment by fr1kker** [comment]
I replaced all gzdoom files except for wads, and I'm still having the same issue

**Comment by boogiebogus** [comment]
what exactly do you mean by "except for wads"?

probably the most important file for this is your .ini, so try deleting that as gzdoom will generate a new one.

**Comment by fr1kker** [comment]
When I say "except for wads", I meant the wads in the GZDOOM folder. These being DOOM.WAD, DOOM2.WAD, CHEX.WAD (chex quest, which isn't used in the wadsmoosh compilation), and NERVE.WAD.
Also there's a high chance the ini has something to do with it, so I'll try deleting that file.

**Comment by fr1kker** [comment]
Loadouts are now working properly. Thank you for your help.
