### ISSUE TITLE
Use + Unload on HERP does not drop the first mag.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#115]
If you only use the combo without holding Unload, it will put the mag in your inventory anyway. Any subsequent usage of Use + Unload will drop the mags as expected.

**Comment by MatthewTheGlutton** [comment]
It's a side effect of the fact that holding Use also has you pick up what you've just dropped.

For comparison, try:
- hold Use, tap Unload, see pickup, let go of both, press and hold Use again, tap Unload
- hold Use, tap Unload, immediately let go of both, drop

I'd do something about this, except it would conflict with other interfaces...

**Comment by Accensus** [comment]
Oh, right. That makes sense. Letting go of both keys works fine. Thanks!

**Comment by MatthewTheGlutton** [comment]
Also, just a reminder you only need to hold Use to unload a mag if it isn't sealed.
