### ISSUE TITLE
You can medikit friendly marines, but can't stim them.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#117]
Unless that's intentional.

**Comment by MatthewTheGlutton** [comment]
Intentional for now since I really don't have the energy to work out just how a mob should even react to stims - most of the benefits relate to things that are abstracted out as it is.

**Comment by Accensus** [comment]
I was thinking friendly marines would get up faster if incapped. As for smaller enemies, perhaps hitting them with two stims would kill them?

**Comment by MatthewTheGlutton** [comment]
Not going to do berserk unless you guys actually want to randomly face zerked marines...
