### ISSUE TITLE
Brutal Bolognese mod- Invisible enemies

### ISSUE THREAD

**Issue by fr1kker** [MatthewTheGlutton/HideousDestructor#118]
Running this with the Brutal Bolognese mod allows you to gib cacodemons and barons of hell/hell knights- but if they're faking their death / incapacitated, when they come back they're invisible. No way to disable the mod without restarting the save AFAIK.

**Comment by boogiebogus** [comment]
that's just a brutal bolognese thing.

**Comment by fr1kker** [comment]
> that's just a brutal bolognese thing.
There's no way to disable gibbing in the mod's options. I can set the minimum gibbing health to -100, but that still causes the enemies to be gibbed almost immediately when hit with a burst/automatic weapon.

**Comment by MatthewTheGlutton** [comment]
Do not run HD with brutal anything.
