### ISSUE TITLE
Allow slot wrapping if no grenades are present.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#120]
Right now grenades switch to fist if there are no grenades present in your inventory, but that essentially locks the weapon selection to a single direction and that's forward. I have an SMG and a Boss rifle, plus a few weapons inbetween. It's faster to go backwards when selecting from SMG to Boss, i.e. SMG -> Fists -> Bandage -> Boss than it is to go forward.

Honestly this is kind of a nitpick and I could just press 8 and switch to the Boss. Reporting just in case.

**Comment by MatthewTheGlutton** [comment]
I've addressed this by causing the autoswitch only to happen if you're pressing fire or altfire.

Making a note to myself: that same commit also fixes the flickering left knuckle on the Freedoom punch.
