### ISSUE TITLE
Dropped spoon looks weird.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#121]
Probably palette fuckery. I don't think it's supposed to look like this, though:
![Screenshot_Doom_20200305_122718](https://user-images.githubusercontent.com/24256978/75972868-d6ee9f00-5edc-11ea-9328-c8a916dd50f9.png)

**Comment by MatthewTheGlutton** [comment]
That's pretty much how it always looks as far as I can tell.
