### ISSUE TITLE
Low-density projectiles don't lose speed correctly

### ISSUE THREAD

**Issue by boogiebogus** [MatthewTheGlutton/HideousDestructor#125]
![image](https://user-images.githubusercontent.com/53976699/76566861-0cb6f900-6484-11ea-88e8-6b5567f82462.png)
As can be seen in the image, the wad of the shotgun somehow manages to travel 300 meters with decent accuracy.

This is obviously very realistic for a lightweight, completely non-aerodynamic object to do this.

**Comment by MatthewTheGlutton** [comment]
Renaming this status because I had to remind myself that at this point each bullet actor class has its own properties with no general physics to translate into results, so the underlying problem for now is that the #s for the wad are wrong...

**Comment by MatthewTheGlutton** [comment]
::looks at the numbers::

disregard my previous comment

**Comment by MatthewTheGlutton** [comment]
::squints at the deceleration code::

or maybe i was right the first time

how's it looking now?

**Comment by boogiebogus** [comment]
![image](https://user-images.githubusercontent.com/53976699/76571620-4f7dce80-648e-11ea-81f3-b0b9feca9608.png)
a little better, but still not great.

**Comment by boogiebogus** [comment]
for some reference:

> A wad is abandoned with every shot fired, and there is no practical way to recover spent wads which typically travel 30-50 yards.

**Comment by MatthewTheGlutton** [comment]
...I was really not expecting it to make that little a difference. Will crank this up even further and reduce speed as well.

and damn even more microplastics :(
https://www.vims.edu/ccrm/research/marine_debris/problems/plastics/shotgun_wads/index.php

**Comment by boogiebogus** [comment]
![image](https://user-images.githubusercontent.com/53976699/76572258-f3b44500-648f-11ea-9404-9c07231951fe.png)

that seemed to do the trick. the wads travel a little before stopping and gradually floating to the ground.

**Comment by boogiebogus** [comment]
the only issue is that such a slow traveling projectile somehow makes a bullet puff.

**Comment by MatthewTheGlutton** [comment]
Seems like I never actually implemented the conditional puff types for the base bullet actor.

No idea if these numbers are any good at all, but it does at least try to do the thing now.

**Comment by MatthewTheGlutton** [comment]
Had to slow the thing down by a lot to make it look anything other than very very bad.
