### ISSUE TITLE
Unclamp hd_encumbrance.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#126]
If someone changes a CVar via the console, 
99% of the time they know what they're doing. Might be a good idea to unclamp any other clamped slider-based CVars following the same reasoning.

**Comment by MatthewTheGlutton** [comment]
I recall there was a reason for a lot of these clamps, encumbrance in particular. Like, actual glitches and shit. I can't see anything now though.

Damage is already unlimited, killer barrels shouldn't go above 100% (oops all), and I think the other stuff (e.g. crosshair scaling) kinda has to stay within a certain range to make sense.
