### ISSUE TITLE
Lightbearer dies on spawn even if there is clearly enough space.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#129]
Can be tested on range. I reproduced it with the Boss rifle, dunno if it's projectile-related. Spawn a few invulspheres and shoot them. There's a 50% chance the Lightbearer will die instantly even if there's enough room.

**Comment by MatthewTheGlutton** [comment]
Apparently the explosion effect was killing it??? Or something.

Adding a 1-tic delay before spawn seems to deal with it.

**Comment by Accensus** [comment]
Happened again earlier today. It's much less common now, though. I can test more later if I don't forget.

**Comment by MatthewTheGlutton** [comment]
It is only with the invuln spheres?

**Comment by Accensus** [comment]
Yep. Don't recall seeing it in any other shape or form.

**Comment by MatthewTheGlutton** [comment]
Looks like it was a case of the hits tracker not being initialized by the time the damage was being done, meaning the death sequence was triggered because 1>0.

I think it's fixed now but please check.

**Comment by Accensus** [comment]
Sorry for the late test; couldn't play yesterday.
Seems to be fixed. Spawned a bunch of invuln spheres and shotgunned them. I'll report if it happens during normal gameplay.

**Comment by MatthewTheGlutton** [comment]
Seeing as the number-initialization seems to have been the underlying issue for the original report I think I'll close this for now.
