### ISSUE TITLE
Lightbearer death flames target the player.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#130]

**Comment by MatthewTheGlutton** [comment]
Fixed by having the player not getting hit :V 

As far as I can recall this was always intended to be a hazard, given the character probably isn't in full subjective control at the moment.

If they're clearly intentionally targeting the player though then that might need fixing.

**Comment by Accensus** [comment]
Just tested, they do home in on the player.

**Comment by MatthewTheGlutton** [comment]
Seems like a limitation of seeker missiles.

I don't feel like doing a real fix for an effect I never really liked anyway so it's gone.
