### ISSUE TITLE
Add command to disregard safety and forcefully detonate IEDs.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#131]
Sometimes that's the only way to get out of a sticky situation. I'd rather get shredded by shrapnel and have a miniscule chance of survival than getting set on fire by 20+ imps from all around.

**Comment by MatthewTheGlutton** [comment]
I've removed this feature entirely since on further reflection this also leads to a lot more unpredictable unexploded munitions littering the area.
