### ISSUE TITLE
Can't drag barrels.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#132]
I remember there was a commit about preventing kicks from moving the barrels. Might be connected.

**Comment by MatthewTheGlutton** [comment]
Does it fail to have any feedback at all, or is there randomized pushback like with a struggling monster?

**Comment by Accensus** [comment]
The "dragging object" text appears but moving around does nothing

**Comment by MatthewTheGlutton** [comment]
And it's only barrels, right? What about non-solid things like weapons and corpses, and solid decorations like floor lights?

**Comment by Accensus** [comment]
Just the barrels. Haven't tested it on weapons, but I was able to drag corpses so I assume there would be no issues with the weapons. I could also drag torches.

**Comment by MatthewTheGlutton** [comment]
I've just tried summoning barrels (killer and innocent) on the range. Works for me - unless the hitbox is overlapping something so it's stuck.

Could that be the problem?

**Comment by Accensus** [comment]
Honestly I have no idea. I don't even remember where I found that "stuck" barrel. May have been just that barrel in particular. I guess this can be closed. If I encounter it again, I'll do am_cheat 3 to see if it's a hitbox issue and post about it.
