### ISSUE TITLE
Heartbeat indicator is not square.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#136]
In a relaxed state, the indicator is a rectangle, which wasn't the case prior to the refactor.

**Comment by MatthewTheGlutton** [comment]
Looked square enough to me with hud_aspectscale set to true, so I'm assuming the problem is when it's not true.

Added a check similar to the one I just added to the revolver.

**Comment by Accensus** [comment]
Yeah, I play with hud_aspectscale 0. Thanks for looking into it.
