### ISSUE TITLE
Health status colors are too dark/saturated.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#137]
Since alpha was introduced, some colors appear darker than intended. I did some tests and and these are the values I found most optimal (that also resemble the old colors):
Health > 33: `color(alf,255,255,96)`
Health <= 33: `color(alf,255,16,16)`

**Comment by MatthewTheGlutton** [comment]
I did notice there was a difference but frankly I *like* the new colours, so unless they turn out to be really hard to see during play I think I'll keep them.

**Comment by Accensus** [comment]
The yellow color is not that bad, but I find the red color to be a bit *too* dark, and due to the alpha it's hard to see how much blood you have.

**Comment by MatthewTheGlutton** [comment]
For the record, after some thoughts I've come to agree, as per my update last night.
