### ISSUE TITLE
Key combo to chamber round from pockets.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#138]
Attempting to reload a pistol or SMG (probably even a Liberator; haven't tested) without any mags available would instead chamber a round from your pockets. Can this be replicated with a keypress or combo like Use + Reload?

Use case: reloading an empty gun automatically chambers a round, resulting in 29+1. I generally prefer having 30+1, but the only way to do on an empty gun is to insert a mag, take it out, add 1 round, and reinsert it.

**Comment by MatthewTheGlutton** [comment]
Agreed, this is long overdue.

Any suggestions?

**Comment by Accensus** [comment]
If you mean suggestions on the key combo, I think Use + Reload should be good. Was going to suggest Alt. Reload, but that is already used as Quick Swap on the pistol. Use + Reload is the only combination that's not used in any of the 3 weapons that support the mechanic (Pistol, SMG, Liberator).

**Comment by MatthewTheGlutton** [comment]
Done, but forgot to close this until now.
