### ISSUE TITLE
Medikit not working properly

### ISSUE THREAD

**Issue by Vladimir999** [MatthewTheGlutton/HideousDestructor#140]
I am playing on LZDoom 3.85, using the latest version of the mod (4.3.3d). Everything works good and no problems, except i am unable to run diagnostic (maybe even treat burns, but i can't tell anyway without diagnostic), and holding "Use" with the medikit it says:
"When holding: 
Nothing - treat wounds"
And i can't find the keybind to treat wounds; i can use bandages, but i know there is supposed to be a staple function somewhere.
Thanks in advance

**Comment by MatthewTheGlutton** [comment]
Huh?

Can you please restate the problem with:
1. Exact steps taken to reproduce the bug
2. Expected result
3. Actual result

**Comment by Vladimir999** [comment]
Using the latest LZDoom, and the latest Hideous Destructor.
After being shot i use the bandages to stop the bleeding, and then i open the medikit.
Then i hold the button that is supposed to show diagnostics (that show percentage of bandaged wounds or burns)
But nothing shows up.

**Comment by Accensus** [comment]
Are you using Blursphere at the same time?

**Comment by Vladimir999** [comment]
No, at the very beginning of the level, and no additional mods or wads.

**Comment by Vladimir999** [comment]
Oh i feel stupid now... i was supposed to hold alt-fire instead of fire... i am not a smart man.
Well now that's solved, but it's just stuck at "scanning, please wait..."

**Comment by Vladimir999** [comment]
Using alt-fire when holding the firemode key uses the diagnostic scanner on someone else, so i'm back to square one

**Comment by aradiel** [comment]
To use diagnostic on yourself you have to hold the firemode key and then press the primary fire key. Always use the primary fire key to apply medical actions on yourself, the action will depend on the other keys you hold, as shown in the instructions when you hold the USE key:

Primary Fire = Apply on yourself
Altfire = Apply on others
+
no other key = heal wounds
Zoom = heal burns
Firemode = Run Diagnostics

I hope this helps

**Comment by Vladimir999** [comment]
I really wish this helps, but that is my original problem: i hold the firemode key and press primary fire, but no diagnostics pop-up, it's just normal heal.
Could it be some incompatibility with LZDoom?

**Comment by aradiel** [comment]
This might sound unrelated, but are you playing with Doom's software rendering or opengl-accelerated graphics? When I tried to replicate your issue, I noticed the medkit doesn't work in software mode because the game doesn't let your character look down enough to apply the medkit, I think that might be your issue.

**Comment by MatthewTheGlutton** [comment]
Now that you mention it, that's almost certainly the issue.

IIRC there is a way to check this in ZS, I'll see if I can incorporate that here.

**Comment by MatthewTheGlutton** [comment]
I think 11c0516 should address this

**Comment by Vladimir999** [comment]
Yes, i am using software renderer... if that's the case, then this is solved

**Comment by Vladimir999** [comment]
But the thing is, i have to use software renderer due to hardware limitations

**Comment by Vladimir999** [comment]
Not sure if you fixed it or not, but i downloaded the mod again and it still doesn't work

**Comment by aradiel** [comment]
Make sure you're downloading the master branch and not the release version.
![image](https://user-images.githubusercontent.com/22911153/79582726-886b1d80-80a2-11ea-9141-c3d48fbc17e9.png)
This will give you a zip with all the new changes before the next release, including the fix. You should be able to load the zip file into LZDoom and play with the fix Matthew mentioned.

**Comment by Vladimir999** [comment]
Got it, thanks everyone!
