### ISSUE TITLE
Keycards not visible in software renderer

### ISSUE THREAD

**Issue by Vladimir999** [MatthewTheGlutton/HideousDestructor#141]
The keycards are only visible when looking at the front of the sprite (i guess), when looking at the back they are invisble. I first noticed this when playing Map02 of Doom TNT, i spent 10 minutes looking for the red keycard and accidentally noticed this.
![Screenshot_Doom_20200417_165305](https://user-images.githubusercontent.com/5247950/79582493-18718d00-80cc-11ea-88b9-fd2fcbe9e47b.png)
![Screenshot_Doom_20200417_165314](https://user-images.githubusercontent.com/5247950/79582505-1d364100-80cc-11ea-9b75-7782535a67e8.png)

**Comment by MatthewTheGlutton** [comment]
Isn't there some kind of fallback for wallsprites???

**Comment by Vladimir999** [comment]
Not sure what you mean by that, sorry

**Comment by MatthewTheGlutton** [comment]
This seems like the software renderer just... isn't bothering with wallsprites. I'm a bit surprised that it wouldn't have any sort of fallback like rendering the sprite normally or something.

I'd like to see if there's any native handling of this problem before trying to hack my way out of it.

**Comment by MatthewTheGlutton** [comment]
Okay, I'm an idiot, I just realized the top screenshot must also be software, this isn't a comparison of gl/vulk versus software just two different angles.

This was dealt with in hardware renderer by having all keys emit light, but obviously that's not an option here.

I'll look into possible alternatives.

**Comment by MatthewTheGlutton** [comment]
Making the cards lie on the ground. Does this work?

**Comment by Vladimir999** [comment]
Yup, great work!
