### ISSUE TITLE
Create bulk limit for backpack generation

### ISSUE THREAD

**Issue by boogiebogus** [MatthewTheGlutton/HideousDestructor#142]
On 0 encumbrance, some absolutely ridiculous backpacks can spawn.

![image](https://user-images.githubusercontent.com/53976699/79602475-8744eb00-80b8-11ea-9b67-7dcda365a99c.png)

It would probably be a good idea to add a bulk limit so that this stuff doesn't happen a lot.

**Comment by MatthewTheGlutton** [comment]
....this is surprisingly difficult to solve.

What happens is that there's a loop that just spawns items and stuffs each one into the backpack, and if the stuff-into-backpack check fails the object left over is destroyed.

Meanwhile, that check is dependent on other bulk checks that have the encumbrance multiplier built right into them.

I wonder if there's a way to temporarily set custom server cvars...

**Comment by MatthewTheGlutton** [comment]
I've made the number of passes the backpack does for this scale in proportion to hd_encumbrance, to a minimum of 1 pass.

This can still result in odd results, but we're already dealing with bending spatial expectations with this cvar.

**Comment by MatthewTheGlutton** [comment]
In the absence of any glaring bugs I think I'll close this.
