### ISSUE TITLE
No blood pressure bar

### ISSUE THREAD

**Issue by Vladimir999** [MatthewTheGlutton/HideousDestructor#143]
There should be a bar next to my heartbeat that shows what i think is my blood pressure. This issue started when i downloaded the master zip file.
![Screenshot_Doom_20200418_121350](https://user-images.githubusercontent.com/5247950/79635063-e6fdcd80-816e-11ea-91be-ba6a62ea85de.png)

**Comment by MatthewTheGlutton** [comment]
I haven't touched that at all recently, other than with the general overhaul.

Are you having any issues with the encumbrance counter on the far left? (Hold Use for the full inventory HUD)

**Comment by Vladimir999** [comment]
Not sure, i'm not really paying a lot of attention to encumbrance, but now that you mentioned it, i think there is no encumbrance bar either, just the number, but i'm not sure, i'll have to check that later

**Comment by MatthewTheGlutton** [comment]
![idfa44holduse](https://user-images.githubusercontent.com/24984517/79678361-9064b380-81af-11ea-9453-bd7d880884e8.jpeg)

Here what it looks like for me if I type IDFA, select the Vulcanette, then hold Use.

Which HUD elements are missing on your end?

**Comment by Vladimir999** [comment]
![Screenshot_Doom_20200419_125328](https://user-images.githubusercontent.com/5247950/79685960-e16eb900-823c-11ea-9c63-1b0f6f66979e.png)
As you can see here, i have no encumbrance bar (but the number still shows), and i also don't have the blood pressure monitor (which should be to the left of the heartbeat)

**Comment by MatthewTheGlutton** [comment]
Looks like it was what I suspected - software doesn't support fill() with opacity values under 255.

I have no idea if I should even try to fix this or if it should be better considered an GZDoom/LZDoom issue...

**Comment by Accensus** [comment]
Seems like a strange limitation. Might be worth reporting.

**Comment by Vladimir999** [comment]
Personally, i don't think you should try and fix it, if you have other things to do, go ahead and do those, this doesn't make the game unplayable. Besides, i have a debug hud installed and it shows much more useful stuff. Do i close this issue then?

**Comment by Vladimir999** [comment]
But then again, it worked in 4.3.3d, now i have the master zip. It was not a problem before, which is weird.

**Comment by MatthewTheGlutton** [comment]
That's because the latest release uses a single-pixel graphic and stretches it out to make the bars, instead of using the current native function.

This is a really odd regression.

**Comment by MatthewTheGlutton** [comment]
Works fine in GZDoom software :S

**Comment by Vladimir999** [comment]
Alright then, thanks anyway!

**Comment by drfrag666** [comment]
https://forum.zdoom.org/viewtopic.php?f=231&t=62157&start=390#p1147783
