### ISSUE TITLE
Chamber loading doesn't always work.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#144]
It works if you take out the mag and unload the chamber, but not when you fire all of your rounds. Can reproduce with all chamberable weapons (Pistol, SMG, Liberator). Dump a full mag and press Use + Reload. If you have another mag, the standard reload animation will play instead.

**Comment by MatthewTheGlutton** [comment]
Fixed.

Liberator turned out to be unaffected, it's just that you needed to pull out the mag first because that's the only way to reach the chamber.
