### ISSUE TITLE
New hud fill() call doesn't use team colour.

### ISSUE THREAD

**Issue by MatthewTheGlutton** [MatthewTheGlutton/HideousDestructor#146]
If you know how to fix this let me know.

**Comment by Accensus** [comment]
Doesn't seem to work in 4.3.3d either.

**Comment by Accensus** [comment]
Try GetColor() or GetDisplayColor(). [PlayerPawn stuff.](https://github.com/coelckers/gzdoom/blob/994550fb006c11f68d7fd62de462010000b2456e/wadsrc/static/zscript/actors/player/player.zs#L2702)

**Comment by MatthewTheGlutton** [comment]
They definitely used to work at some point in the past...

**Comment by MatthewTheGlutton** [comment]
It is done.
