### ISSUE TITLE
Non-HD attacks don't reduce armor durability.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#147]
Here's the situation: I'm playing City of the Damned: Apocalypse on 3.0 damage (because no HD enemies) and am encountering the issue where the armor reduces the damage done to you but it doesn't lose durability when you get hit. Is this fixable? Perhaps a compatibility option can be added?

(I am aware of Universal Destructor's existence but have chosen not to use it for reasons.)

**Comment by MatthewTheGlutton** [comment]
I do not believe there's any code right now to degrade armour if it's not one of several predefined types. Will look into it.

**Comment by MatthewTheGlutton** [comment]
I've just pulled some numbers out of my ass and made the spread ridiculously random since this can be just about anything...

**Comment by Accensus** [comment]
Thanks. I'll check it out tomorrow/later and report back.

**Comment by Accensus** [comment]
Ok so it plays fairly ok on 3.0 damage mult. But I do find that the standard 5-15 damage most hitscanners do barely reduces armor on 1.0 mult. For reference, I lost about 100 green armor after taking about 2050 damage in the range 5-15.

**Comment by MatthewTheGlutton** [comment]
Messed with the numbers based on this feedback.

**Comment by Accensus** [comment]
Seems to be much better now. Thanks!
