### ISSUE TITLE
What are the most common compatibility problems with custom maps?

### ISSUE THREAD

**Issue by MatthewTheGlutton** [MatthewTheGlutton/HideousDestructor#148]
Further to Cali's PSA on the Discord I'm trying to get an idea if there are any recurring problems that repeatedly come up that make the game unplayable (in a bad, immersion-breaking way).

Stuff like #147 for example when custom monsters are present.

Please comment and I'll eventually close once it seems all the really big ones are dealt with or dismissed as unfixable.

EDIT: convenience link https://forum.zdoom.org/viewtopic.php?f=43&t=12973&start=7905

And to be clear, I'm not looking for unavoidable design/logistics stuff like "this door closes too soon to reach when the player is anything other than naked and in perfect health", that's what the doorbusters and the popup tip outright telling you to cheat are for, I mean more like monster replacements that just plain don't work or important weapons that can't be picked up, etc.. that simply loading HD last won't help.

**Comment by boogiebogus** [comment]
not sure if this counts, but sometimes cyberdemons just start shooting at nothing for no reason. If this is in a small monster closet it causes extreme lag due to all of the fragmentation calculations.

**Comment by caligari87** [comment]
Overall the most common problem is conflicts between a map's custom actors that might replace the stock actors. Weapons, monsters, items.

While I don't think it's possible to cover *every* possible use case (older maps repurposing a decorative pillar to make a boss monster or something equally weird), there is the `CheckReplacement()` event handler. Using this, it's possible to entirely override any custom inheritance chains another mod might have used. So if a map replaces all chaingun spawns with a custom weapon, this could intercept that and revert back to whatever HD wants to spawn on the chaingun spots.

In theory I think you could write a handler that simply blocks all inheritance chains back to vanilla, so HD's stock replacers aren't affected. 

***

The other most common issue is HD's weapons doing massive damage to non-HD monsters, and conversely non-HD monsters/weapons not causing proper damage to HD players/monsters. For this I think it would behoove looking at [UniversalDestructor](https://github.com/JRHard771/UniversalDestructor) and see what it's doing, then apply the same principles to anything that doesn't match HD's built-in types. 

Again it's not going to be perfect all the time, but would mitigate the need to replace/remove custom actors from maps (ones that don't replace stock vanilla ones, at least). In theory it might even be worth fully generalizing damage / bleeding to a thinker that applies to any monster, including HD's built-in ones.
