### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by Vladimir999** [MatthewTheGlutton/HideousDestructor#149]
This is probably another software render issue, but the zoom on scoped rifles doesn't seem to be working properly. Holding Zoom+Firemode and using mouselook should change the zoom level on scopes, but it's a very minor change for me.

**Comment by MatthewTheGlutton** [comment]
Yeah, it's a software problem, and why HD has been hardware-only for years.

Not sure if it's even theoretically fixable the way I understand the engine to work.
