### ISSUE TITLE
You can lean yourself off a precipice without getting fall damage

### ISSUE THREAD

**Issue by ElonSatoshi** [MatthewTheGlutton/HideousDestructor#150]
How to reproduce:

1. Verify that HD version is v4.3.3c and GZDoom is version g4.3.3
2. `gzdoom -file ~/path/to/git/clone/HideousDestructor/`
3. Use Freedoom 1 as an IWAD
4. Jump off the precipice in E2M1 while holding a rifle
5. Die (Or barely survive?)
6. Restart the game
7. Now, position yourself on the edge of the precipice, standing at full height and holding a rifle, such that leaning will take you off the edge, like this: 
![Screenshot_Doom_20200430_210047](https://user-images.githubusercontent.com/24940510/80776067-fe519900-8b26-11ea-9771-fab4ddea2316.png)
8. Lean off the edge.
9. Don't die.

Expectation: Hideousguy gets seriously hurt for not being careful where he leans.

Reality: Hideousguy somehow hits the bottom without a scratch, landing on his feet like a cat.

There are other ways to fall off the ledge without taking damage. Sometimes I can fall off just by looking around, or push myself off using my weapon.

**Comment by MatthewTheGlutton** [comment]
Does this happen with 4.3.3d as well?

**Comment by MatthewTheGlutton** [comment]
Just tried it now with latest master.

Looks like those brown thingies at the bottom are just enough to make the drop too short to cause damage.

I might keep this in mind if I were to revisit the damage formula someday.

**Comment by MatthewTheGlutton** [comment]
For the record, it is easier to avoid damage when you've got the rifle out, but it's because you lean less and lean slower - I can replicate this while unarmed by very lightly tapping the lean key, but if I just ham-fist the lean key to go all the way I am almost guaranteed to take damage.
