### ISSUE TITLE
Non-HD enemies bleed out too fast.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#151]
Related to #148.
It takes about five 9mm shots to make an Archvile bleed out to death. Sometimes it only takes four. Not sure if anything could be done about this, but I'm reporting it just in case.

**Comment by MatthewTheGlutton** [comment]
I'm testing with a vanilla baron with rifle rounds and it seems a much bigger concern is the obscene amount of temporary cavity damage done by rifles.

Both shall be addressed.

**Comment by MatthewTheGlutton** [comment]
Current update has 8 Liberator shots on a vanilla baron, 12 on an HD one.

**Comment by Accensus** [comment]
Muuuuch better. Thanks!
