### ISSUE TITLE
Suggestion: Making Yokai's sprite use forcebillboard to appear spherical

### ISSUE THREAD

**Issue by physixcat** [MatthewTheGlutton/HideousDestructor#152]
If the Yokai's sprite always faced the player, it would maintain the illusion that it is spherical from all angles, instead of appearing as a flat circle when it's above/below you - which incidentally would make it easier to spot and kill from awkward angles

**Comment by MatthewTheGlutton** [comment]
it's my default so I never even noticed until now!
