### ISSUE TITLE
Use RIFLSIT* for smallest dot.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#154]
There's this sights pack I've made that changes the crosshairs to green, but the smallest dot is red because it doesn't use any of the RIFLSIT* images.

There are two solutions here, the latter of which would be the best imo:
A) Change the dot to use some RIFLSIT image so modders can safely change the crosshairs' color without messing anything up by touching REDPXL.
B) Use Fill() to draw the crosshairs. This will allow the use of a Color CVar as color argument. Being able to use any RGB value would actually be pretty dang neat.

**Comment by MatthewTheGlutton** [comment]
REDPXL copypasted to RIFLSIT0
(any less crude way to do this would take up even more space)

**Comment by Accensus** [comment]
Hey, as long as it works. Thanks.
