### ISSUE TITLE
Antenna sometimes gets stuck inside the ground when incapped.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#156]
Completely preventing you from doing anything. I can't always reproduce it.

If it helps, holding Use shows the Spriting help rather than the Improvised Bandage help which is usually the case when incapped.

**Comment by MatthewTheGlutton** [comment]
What do you mean "stuck inside the ground"?

**Comment by Accensus** [comment]
While physically impossible to do that in the Doom engine, something goes wrong that almost completely prevents you from rotating the camera in any shape or form. Shaking the mouse furiously makes your view twitch, but that's it. I've managed to reach a conclusion that it happens if you are incapped while sprinting. The moment your camera looks at the floor, it snaps at a 90 degree angle as if Satan's grabbed your antenna and is pulling it down. That's probably the best description outside of a video that I can give.

**Comment by boogiebogus** [comment]
I also experienced this once. I couldn't look in any direction until i was out of incap.

**Comment by MatthewTheGlutton** [comment]
Unable to replicate either by a delayed playdead call or letting myself get shot by a zm zombie.

Any clue what sort of thing tends to increase the chances?

**Comment by Accensus** [comment]
Managed to replicate it once a few minutes ago by getting incapped, holding alt-fire, and spamming the fist slot key. This allows you to make small lunges while incapped and also punch stuff. After lunging while looking towards the ground, below the horizon line, the camera got pinned to the ground directly underneath you. I'm still trying to somehow replicate this reliably. I think I've had this happen while crouch-strafing with long weapons, too.

**Comment by MatthewTheGlutton** [comment]
Seems related to the ability to deselect the incap weapon briefly.

I think I may have addressed it.

**Comment by Accensus** [comment]
I'll check it out soon. Thanks!

**Comment by Accensus** [comment]
Tested but forgot to reply, lol. Doesn't seem to happen anymore. Thanks, Matt! I'mma close this then.
