### ISSUE TITLE
Firing range

### ISSUE THREAD

**Issue by Shreddy9** [MatthewTheGlutton/HideousDestructor#157]
Not much of a bug, but the weapons to the left of firing range (the BFG, Bronto...) fall down under the table.

**Comment by Accensus** [comment]
Works fine here, mate. Using 9cb9197539798d35616d69ba5dcafe052f3d618b (latest master as of this post) on GZDoom g4.4pre-132-g2c1a42ae5.

**Comment by Shreddy9** [comment]
Well, i'm using LZDoom, because, hardware limitations.

**Comment by Accensus** [comment]
Even then, I'm not sure if 3D sectors would outright disappear. I thought they'd just not render. Dunno.

**Comment by MatthewTheGlutton** [comment]
Does that table even appear correctly in LZDoom?

**Comment by Shreddy9** [comment]
Yeah, everything is fine now... i probably should have said i have plenty of addons. The issue appears only when i load the newly developed BigDoom. The table is there, i can walk over it just fine, but the weapons that spawn fall through it (i can drop the weapons on it). It's weird that i turned scaling off, i set it to 1,00.
