### ISSUE TITLE
Keycards are hovering.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#158]
Crazy how nature do dat.

![Floaty](https://user-images.githubusercontent.com/24256978/81902847-7dd07500-95c9-11ea-9548-1fdb0f51743d.png)

Can be seen on the range keycard as well. It's definitely not sprite clipping; already checked.

**Comment by MatthewTheGlutton** [comment]
Does it happen in vanilla?

**Comment by MatthewTheGlutton** [comment]
Confirmed it does, in fact, happen in vanilla.

Looks OK in Freedoom since the sprite is so much bigger - I think it was an intentional fix on the FD spriter's part.

No promises whether I'll try to fix this eventually.

**Comment by MatthewTheGlutton** [comment]
After some thought I don't think I'll fix this on HD's end - this is the sort of vanilla issue that any number of aesthetic/fix wads in people's autoloads might have already addressed.

The best way to fix this would be to do whole new sprites and I'd rather not do that at the expense of the original sprites for a glitch that's relatively hard to see and does not affect gameplay.

**Comment by MatthewTheGlutton** [comment]
Doom support will be deprecated going forwards.
https://bethesda.net/community/topic/407885/why-you-should-remove-doom-eternal-from-your-pc-immediately/20
