### ISSUE TITLE
Getting incapped with berserk doesn't allow you to get up.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#160]
Can do it by zerking and lunging into an enemy. Probably even a wall would do it.

**Comment by Shreddy9** [comment]
Weird, works for me just fine, i just tested it

**Comment by Accensus** [comment]
This happens mostly if you're on fire. Easy to test on MAP16 with a berserk kit and buddha mode. I guess the sheer amount of damage incaps you and berserk doesn't ignore that. Strange because I don't recall that happening before. Maybe I wasn't paying attention or maybe this is new.

**Comment by funnymanDELUXE** [comment]
yeah, that happened to me too, i incapped and died even at one point. after that, i decided to spam shift anytime i got incapped while using berserk

**Comment by MatthewTheGlutton** [comment]
That sounds like it is past the damage threshold where you wouldn't be able to get back up even with zerk.

Which seems like overcomplicating things and I'm half considering removing incap entirely when you're zerked... you just keep going until you're so physically broken you die...

**Comment by caligari87** [comment]
Since zerk's closest analogue in terms of performance seems to be PCP, that sounds appropriate.

**Comment by MatthewTheGlutton** [comment]
> berserk kit *and buddha mode*

Gave myself a zerk and buddha mode on the range, then 100 fire.

Managed to spin enough to put out the fire while incapped, but could not get up until I stopped taking damage from the residual heat.

I'm just going to add in a randomized zerk check for the part of the damagemobj call that skips the incap/lifesaving stuff.

**Comment by MatthewTheGlutton** [comment]
I'll assume this has been adequately addressed...

**Comment by Accensus** [comment]
Yep, much better now. Thanks, Matt!
