### ISSUE TITLE
Enemies resurrected on BEAUTIFUL aren't shootable

### ISSUE THREAD

**Issue by caligari87** [MatthewTheGlutton/HideousDestructor#165]
Reported on the discord, monsters that get timer-resurrected on BEAUTIFUL difficulty don't have some proper flag set. Shots just pass through. I believe they're lacking the NOBLOCKMAP flag.

![image](https://user-images.githubusercontent.com/6425795/83381313-94cedf80-a39d-11ea-8152-08b54f7ae8f7.png)

(some mods were loaded for this screenshot but it happens without)

**Comment by ApocDriver** [comment]
Addenum: Shooting at the ground that the enemy is standing on kills the enemy as normal, and it looks like the brown demon things that try to latch on to you and bite you half to death are unaffected.

**Comment by MatthewTheGlutton** [comment]
Seems like BeginPlay isn't called in the respawn sequence even though all of its variables are being reset otherwise.

I don't know why the necessary steps to set the custom live/dead heights was put into a separate BeginPlay override to begin with. I hope it was nothing important.
