### ISSUE TITLE
Ladders cannot be placed from below a ledge

### ISSUE THREAD

**Issue by Holsterbau** [MatthewTheGlutton/HideousDestructor#166]
To my understanding, as it says in the manual, ladders are capable of being placed from below a ledge to scale the ledge.

> From below, stand as close to the ledge as possible and look right into the wall.

No matter how closely I follow these instructions, the ladder will not be placed. The sound of a ladder being placed will play, but the message `Can't hang ladder here` will show up, and nothing else happens. I presume that this is a bug, because not following these instructions correctly or trying to place the ladders in an invalid place will not play a ladder placement sound.

Ladders can be placed from above a ledge normally.

**Comment by MatthewTheGlutton** [comment]
Release or master? There have been some significant changes to the ladder code and this sounds just like a problem I was having last month.

**Comment by Holsterbau** [comment]
It is release, yes. Not master.

**Comment by MatthewTheGlutton** [comment]
And that's my cue to do a new release soon!

Can you replicate the problem with master? If not I'll close this.

**Comment by Holsterbau** [comment]
Just tried master. It still doesn't seem to work.

**Comment by MatthewTheGlutton** [comment]
Please take a screenshot of where it is that it isn't working

**Comment by Holsterbau** [comment]
Sure. Here is an example. None of these ledges can be accessed from below: [](https://i.imgur.com/5lUITJb.jpg)

**Comment by MatthewTheGlutton** [comment]
How tall is that ledge on the left, and have you tried jumping? These seem like they might be just out of range...

**Comment by Accensus** [comment]
That is positively too tall for the ladder. Also the sound has always played, even in much earlier versions.

**Comment by Holsterbau** [comment]
Not sure how to measure the distance, but, no, the ledge on the left cannot be scaled with a jump. Is there supposed to be an upper limit to how far a ladder can extend?

**Comment by Accensus** [comment]
Try to jump-attach the ladder on the ledge to the left. Gotta time it right, but I'm fairly sure you can attach the ladder in that case.

**Comment by MatthewTheGlutton** [comment]
Oops, didn't see the thing about the ladder sound playing even on an abort, will look into that.

**Comment by Holsterbau** [comment]
Well, if there is a limit, it is doesn't seem to be much more above than what a character simply can scale on its own. If this is a feature and not a bug, the issue can be closed, of course. It's just that a lot of maps implement, understandably enough, the usual "pillar bridge" that can only be traversed while going very quickly as a non-hideously destroyed doomguy, but practially impossible or very hard in Hideous Destructor. As you might imagine, the screenshot I posted is example of just that. It would be nice to have a server setting for how far up a ladder can go from below and/or above.

**Comment by MatthewTheGlutton** [comment]
It seems the ladder sound thing, whichever one it is (I can't test this rn and am relying on other players), was intentional.

This feature suggestion is definitely well within "just noclip if the map makes it impossible" territory.

**Comment by ElonSatoshi** [comment]
I'm pretty sure the ladder makes a sound without installing the ladder, and then doesn't make the sound if the ledge is at a certain height. Isn't that a bit inconsistent and buggy?

**Comment by MatthewTheGlutton** [comment]
There was further discussion on Discord:
> leave the ladder sound on failed attempts, please, because that's the metric I've come to know for whether or not a surface can be laddered or whether it's some bizarre un-ladderable surface.

**Comment by Holsterbau** [comment]
I was considering contributing to this project, but your repulsive personality, arrogance, and condescending tone ensured that will never happen.

Good job, and bye.
