### ISSUE TITLE
Extraneous grenade icon on automap HUD.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#167]
![Screenshot_Doom_20200610_224531](https://user-images.githubusercontent.com/24256978/84311840-aae25a00-ab6c-11ea-84d2-0e62bccc61f2.png)

Talking about the one on the right, which is present even if I don't have any grenades in my inventory.

**Comment by MatthewTheGlutton** [comment]
Unable to replicate. The closest I can get is to select grenades, then go into automap, but that's just the selected-weapon icon and it's way off to the left.

**Comment by MatthewTheGlutton** [comment]
Moved the selected-weapon icon out of the ammo block. Hopefully this doesn't look like ass in other screen sizes...
