### ISSUE TITLE
Discrepancy between inserting mags into backpack via mag manager and directly.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#168]
1. Set encumbrance to 2.0 and go to range. The enc is to make things easier, but it's also what I tested with.
2. Spawn an empty backpack, 23 SMG mags, and 7 shotgun shells.
3. Insert 22 SMG mags and all 7 shells into the backpack.
You should be able to insert the 23rd mag directly, resulting in exactly 500 bulk, but you won't be able to do it through the mag manager.

Note that prior to reporting this I managed to do the opposite in a playthrough - I could insert a mag through the manager and go over the backpack's capacity but fail to insert the same mag directly.

**Comment by MatthewTheGlutton** [comment]
I just gave this a try now, no weird stuff from the mag manager bleeding into the backpack interface or vice versa, I think it's fixed.
