### ISSUE TITLE
Item manager items overlap with text.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#171]
![Screenshot_Doom_20200619_225330](https://user-images.githubusercontent.com/24256978/85175413-0ce34380-b280-11ea-9f02-3898837696f9.png)
hud_scale 3, forced 16:9 aspect ratio (if it matters) because 16:10 with 1920x1200 makes the text xbox hueg.

**Comment by MatthewTheGlutton** [comment]
Looks even worse with hud_scale 1 (the mag is overlapping right through the actor name).

How do I get this stuff to follow the text scale?

**Comment by Accensus** [comment]
No solid idea, unfortunately. Hud_scale is technically supposed to scale the text as well, but only if you draw it with Statusbar.DrawString. I don't know what the flags are to allow scaling when using the Screen.* struct. Maybe DTA_HUDRules?

**Comment by MatthewTheGlutton** [comment]
Best option seems to be to just call BeginHUD(forcescaled:true) there. d1b5f3c

Tempted to apply this to the mag manager as well, but nothing's broken if I don't.

**Comment by Accensus** [comment]
Well, seems to work, but now the mugshot is bigger in the item manager as opposed to the rest of the HUD.

**Comment by MatthewTheGlutton** [comment]
Adding another line to reset it.

**Comment by Accensus** [comment]
Looks good now. But incoming another scaling issue. Will open a separate one for it.
