### ISSUE TITLE
Overlap in mag manager with 16:10 @ 1920x1200.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#172]
hud_scale 3

![Screenshot_Doom_20200620_001842](https://user-images.githubusercontent.com/24256978/85180340-df03fc00-b28b-11ea-9b2e-a3bb92e3b573.png)

It looks ok if I set hud_scale to 5, but then everything is absolutely huge.

**Comment by MatthewTheGlutton** [comment]
I think that's my queue to do what I mentioned in #171.

**Comment by MatthewTheGlutton** [comment]
By the way I'm leaving this open just in case some edge case needed to allow scaling, if not I'll close this.

**Comment by MatthewTheGlutton** [comment]
Closing since no one's reported any weird side effects from the changes.
