### ISSUE TITLE
HUD going off screen

### ISSUE THREAD

**Issue by Shreddy9** [MatthewTheGlutton/HideousDestructor#176]
Part of the text in HERP instructions goes off screen, no matter what i set hud_scale to (1280 x 800 resolution)
![Screenshot_Doom_20200625_230903](https://user-images.githubusercontent.com/5247950/85797181-6a253c00-b73b-11ea-87de-fc1baeebc819.png)

**Comment by MatthewTheGlutton** [comment]
That's what I use and it's fine for me. Not sure why it scales so much bigger in LZDoom.

Anyway I've gotten rid of that text since it's so much more maintainable to put all of that info into the use helptext which it's already in anyway.
