### ISSUE TITLE
IdleDummy doesn't disappear.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#177]
It just travels slooooowly. Did `remove idledummy` on MAP30 of TNT after throwing a bunch of grenades and it removed 2500 actors.

**Comment by MatthewTheGlutton** [comment]
I think I've found and fixed the problem. Yokai and ghost marines had IdleDummy set to their blood but those blood actors weren't set to expire. This probably also explains why they have momentum.
