### ISSUE TITLE
[Crash] BFG ammo consolidation on level change can cause "array access out of bounds"

### ISSUE THREAD

**Issue by physixcat** [MatthewTheGlutton/HideousDestructor#178]
**Steps to reproduce:**

1. Equip BFG and backpack. 
2. Place at least one battery inside of the backpack (charge level doesn't matter)
3. Fire BFG.
4. Either keep the spent battery inside of the gun, or unload and throw the battery on the ground. Player shouldn't be directly holding any batteries, they should be in backpack.
5. Trigger a level exit

**Expected result:**
Next map starts.

**Actual result:**
```
VM execution aborted: array access out of bounds. Max.index = 0, current index = 0

Called from HDWeapon.CheckBFGCharge at :zscript/wep/bfg.zs, line 775
Called from bfg9k.Consolidate at :zscript/wep/bfg.zs, line 112
Called from HDPlayerPawn.ConsolidateAmmo at :zscript/player/invhandling.zs, line 14
Called from HDPlayerPawn.levelreset at :zscript/player/player.zs, line 780
Called from HDHandlers.PlayerEntered at :zscript/player/player.zs, line 696
```

**Comment by MatthewTheGlutton** [comment]
Seems like that line was checking the "amount" variable of the BFG itself. Should be fixed now.

**Comment by physixcat** [comment]
:+1: Yeah, looks like it's fixed!
