### ISSUE TITLE
Barrels count for killcount

### ISSUE THREAD

**Issue by mmaulwurff** [MatthewTheGlutton/HideousDestructor#179]
Issue found by HexaDoken and Accensus (putting it here from Discord so it doesn't get lost):

> HD barrels have +countkill because they inherit from hdmobbase which has monster combo, however barrels are not actually monsters
> but because they have countkill the level info screen will incorrectly count them as monsters

> Which also means that possessed barrels count for two kills.

**Comment by MatthewTheGlutton** [comment]
Fixed earlier today
