### ISSUE TITLE
zandronum port?

### ISSUE THREAD

**Issue by Antiswitcher** [MatthewTheGlutton/HideousDestructor#180]
Most mods work with zandronum if they work on gzdoom. Is there a zandronum port, or am I attempting to load the file wrong (linux)? typically when loading a file from zandronum you must do "-file file.extension" for each mod you want to load.

**Comment by beatcrazed** [comment]
Hideous Destructor does not work with Zandronum, and wont until zandybam supports Zscript. Unfortunately that makes multiplayer a hassle, but that's what we sacrifice for advanced features. 

Technically there are versions of HD from 2012 and 2014 which will run in Zandronum, but they have their own problems in multiplayer. If you're just after singleplayer grab the latest version of HD and whatever release is currently out for GZdoom. If you're after multiplayer then I'd recommend joining the Hideous Destructor discord. We can help you get set up there.

**Comment by Antiswitcher** [comment]
I'd love to play multiplayer with this! Where would I find the HD discord?

**Comment by beatcrazed** [comment]
Right, here we go. You'll have to forgive me for the delay: It's been so long since I joined that I had to ask around for where the permanent invite even is.

https://discord.gg/Cfef6jE

Welcome to the party!

**Comment by ApocDriver** [comment]
There's also a permanent invite link on the ZDoom forum thread for HidDesous, by the way.
