### ISSUE TITLE
Could holding use auto-equip rad suits?

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#182]
This is a feature suggestion, for the record. In some situations equipping a rad suit asap is critical to survival.

**Comment by caligari87** [comment]
There's too many other situations where holding Use is necessary, checking your expanded HUD for example, or displaying helptext. Any delay long enough to avoid accidentally putting on a radsuit, would also be longer than scrolling your inventory and using the radsuit.

**Comment by MatthewTheGlutton** [comment]
The problems are the same for armour as a radsuit, it's just the radsuit slows you down even more and wearing it while under fire endangers the suit more than happens with armour.

I'm going to add this, and also for the jetpack too - I'm not sure about the latter.

**Comment by ApocDriver** [comment]
What if i hold the "use" key to use the sights? (For some reason I can't fire the Slayer's second barrel and aim down the sights with Mouse2 at the same time so I do that instead)

**Comment by MatthewTheGlutton** [comment]
Check your keybindings and read the manual.

**Comment by ApocDriver** [comment]
Okay, I don't think it's actually a Hideous Destructor problem, I think my mouse is just incapable of pressing Mouse 2 and Mouse 5 at the same time. Ah well.

**Comment by caligari87** [comment]
Whoops, I thought this was asking to auto-equip a radsuit in your inventory if you hold `Use` in general, not holding `Use` *while picking up*. Ignore me, I'm an idiot and yes, this makes perfect sense.

**Comment by ApocDriver** [comment]
Oops, I thought the same thing. Never mind, this sounds perfectly fine.

**Comment by MatthewTheGlutton** [comment]
Oh, okay then!

I thought this was (and this is my own concern) about some of us who tend to lead-finger our keys and sometimes accidentally hold instead of tap.

Which hasn't really been an issue for armour since 90% if you're not wearing armour you should be, so I'm still a little concerned about accidentally putting stuff on with this more specialized gear...
