### ISSUE TITLE
Question about the zoom state

### ISSUE THREAD

**Issue by physixcat** [MatthewTheGlutton/HideousDestructor#183]
I bound a little command to allow the player to toggle zoom instead of having to hold the button. I also added the range finder to it, but that's not relevant to the question. Just something similar to the "silent walk/run" toggle other people have used (so it doesn't print the value of `cl_run` to messages)

```
[Doom.ConsoleAliases]
Name=zoomrf_on
Command=+zoom;wait 10;hd_findrange;alias zoomrf_tog zoomrf_off
Name=zoomrf_off
Command=-zoom;alias zoomrf_tog zoomrf_on
Name=zoomrf_tog
Command=zoomrf_on
```
```
Mouse3=zoomrf_tog
```

However, I have found that the zoom state persists through player movement - ie, if the player reaches a certain speed, the zoom is suspended but it comes back after slowing down, because `-zoom` was never called. You have to manually toggle it off. Weapon switching while in this state also does not call off the zoom, sometimes it locks you into the weapon or simply switches to the other one while maintaining zoom.

So, I meant to ask: is there some non-invasive way I could force reset zoom for certain actions, say in a small personal patch loaded after Hid Dest? Or would it require reworking to how zoom works in the codebase?

**Comment by MatthewTheGlutton** [comment]
Most of HD's code just checks for whether the input flags include BT_ZOOM.

From what you're describing the game engine is assuming that the zoom button is continuing to be pressed.

I really can't think of any way to get around this without creating all sorts of side effects or requiring a whole separate custom keybind.

**Comment by physixcat** [comment]
Understood. I'll be closing this now
