### ISSUE TITLE
Add flag to HDMobBase to prevent monsters from getting lit on fire from blur

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#186]
I've encountered an issue with the follower mod I'm making, and that's blur setting the follower on fire. I don't think I can add `-ISMONSTER` because of all the side effects that may or may not come with it, like enemies not targeting the follower. I am not actually sure if that will happen, but I'd still like to avoid any side effects if possible.

**Comment by MatthewTheGlutton** [comment]
This is... surprisingly thematically appropriate.

**Comment by Accensus** [comment]
Just to clarify, I meant a flag that's disabled by default, but one that coukd be set on a class that inherits from HDMobBase. This wasn't a suggestion to outright disable blur's effect for everything. Suggested it because the follower is supposed to mimic a player more than a standard NPC, and players aren't lit on fire, as far as I know.
