### ISSUE TITLE
Make the NVG shaders only effect the rendered scene

### ISSUE THREAD

**Issue by boogiebogus** [MatthewTheGlutton/HideousDestructor#187]
![image](https://user-images.githubusercontent.com/53976699/88321779-b4272080-cced-11ea-8f89-d300425f27bb.png)
As can be seen in this screenshot, putting on NVGs makes the hud nearly impossible to use. I understand that there are reasons why the NV effect is a screen shader, but recent changes make night vision nearly unusable. You are basically forced to use truecolor mode since that is the only one where you get some semblance of a readable hud.

**Comment by boogiebogus** [comment]
i've been told on discord that there are some problems with having it be a scene shader. however, i don't think that having the hud be like this is a good compromise, so i'm thinking of potential solutions right now.

**Comment by caligari87** [comment]
I know we discussed in Discord, but just summarizing here: I set up these presets to preserve what I feel is HD's existing design goal with the NVGs, being a tradeoff between visual acuity and ability to see in the dark. For what it's worth, I and many others have been using this shader as an addon for over a year and haven't been bothered with the HUD issue, it just takes getting used to. 

That said, I can imagine there's always room for balance improvements and tweaks.

I set up the "Hideous" NVG style to match what I feel was the intended visual style of the original NVGs, with a more consistent treatment of scanlines (having them linked to the pixel size, specifically). This one I'll leave to @MatthewTheGlutton's discretion for tweaking the specifics, as I know he has a certain intended vision (ping me if you need assistance with the numbers)

As for the other styles, some good candidates for better visual acuity would be the "Modern" and "Truecolor" options, being as they represent higher technological advancement than the "Analog" and "Digital" styles. Maybe bumping those up to a resfactor of 2 (half-res) would be sufficient.

**Comment by MatthewTheGlutton** [comment]
IIRC there's no other way to make the sight picture be affected by the shader. The total inability for it to be affected by ambient light is bad enough.

Beyond that, I have no strong opinions on the NVGs besides a gut feeling they shouldn't be *too* convenient.

Closing this since any further discussion on the NVGs are probably better served with specific issues.
