### ISSUE TITLE
Simultaneously emptying and dropping a mag/clip with only one mag/clip available crashes the game

### ISSUE THREAD

**Issue by swissarmybox** [MatthewTheGlutton/HideousDestructor#19]
Video demonstration:
https://youtu.be/Gw5my-QnIa8

**Comment by MatthewTheGlutton** [comment]
Can you screenshot that? The Youtube buttons are getting in the way of the console lines I need to read.

**Comment by MatthewTheGlutton** [comment]
Also I can't see what you did at all, or replicate it based on your description. Can you tell me exactly what controls you hit?

**Comment by MatthewTheGlutton** [comment]
Nevermind, just increased youtube to "cinema" mode and could see the offending line location, should be fixed now.

How do you even time that anyway? Alias?

**Comment by MatthewTheGlutton** [comment]
I think any further bugs that look like this would be cause by something different enough to warrant a new issue, so I'll close this.
