### ISSUE TITLE
Resurrection by blues can "resurrect" living enemies.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#191]
Which of course fails to actually resurrect them, but it still makes them friendly. CanResurrect doesn't imply "dead". In fact, from the looks of it, CanResurrect simply returns `true` if not overridden.

**Comment by MatthewTheGlutton** [comment]
Yes, it does occasionally make mobs friendly.

Is it doing anything else glitchy though?

**Comment by Accensus** [comment]
Nope, just that. I thought this was only supposed to happen when the dedicated conversion occurs.

**Comment by MatthewTheGlutton** [comment]
Nope, random friendlies are intended.

**Comment by Accensus** [comment]
Just to make sure, this allows enemy archviles, cyberdemons, masterminds, etc to be converted to friendlies. Is *that* intended? This report is for `case 0`, not `case 1`.

**Comment by MatthewTheGlutton** [comment]
No boss monsters then. Fixed.
