### ISSUE TITLE
Virtualize max blood amount.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#192]
The idea is to be able to change the amount of blood a monster has without having to increase the health. One use case for this is my follower mod where the follower has 200 health and thus 200 blood, but I'd like to request a way to increase the max blood amount without having to replace DamageMobj entirely (which would result in copy-pasting for the most part, and copy-pasting is evil).

Best case scenario I'm able to override GetMaxBlood() or whatever and return, say, 400.
That, or it could be a property. All the same to me.

**Comment by MatthewTheGlutton** [comment]
Added property `hdmobbase.maxbloodloss`.

(These properties implicitly default to zero, right?)

**Comment by Accensus** [comment]
Yeah, variables defined on the class always get initialized to zero, null, empty, etc.

**Comment by MatthewTheGlutton** [comment]
Sweet.

Unless I forgot a closing bracket or something it's good to go.

**Comment by Accensus** [comment]
I'll give it a shot soon. Thanks, man! I appreciate it.
