### ISSUE TITLE
HDPickup ignores NOTINPOCKETS flag when picking up items.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#195]
To test this, add `+HDPICKUP.NOTINPOCKETS` to PortableLiteAmp and fill your pockets with any ammo, then spawn the NV goggles. Trying to pick them up will fail.

**Comment by MatthewTheGlutton** [comment]
I've completely forgotten where and how that flag is used. Does it appear anywhere else besides armour?

**Comment by MatthewTheGlutton** [comment]
Does this bug happen for an item that does not inherit from HDMagAmmo?

**Comment by Accensus** [comment]
Yeah, I actually discovered it on my teleporter item, which inherits directly from HDPickup. Gave PortableLiteAmp as an example so you don't have to download external addons.

**Comment by MatthewTheGlutton** [comment]
I think 216af6e should address this.

**Comment by Accensus** [comment]
Seems to work just fine so far. I'll report if I find any side effects.

**Comment by Accensus** [comment]
The side effects strike. MaxAmount is now disregarded just as if the item had +INVENTORY.ALWAYSPICKUP. Except it doesn't, but I can still pick it up past the limit (which of course does nothing but waste the item).

**Comment by MatthewTheGlutton** [comment]
Should be fixed now.

**Comment by Accensus** [comment]
Can confirm, works just fine now. Thanks!
