### ISSUE TITLE
Add a second return value to GetSBarNum().

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#196]
Use case: change the color based on a condition. For example, I'd like to change the color from cyan to green when the teleporter index matches an existing beacon.

However, this will probably break existing mods that override it. The alternative solution is to introduce a separate virtual for retrieving the color.

**Comment by MatthewTheGlutton** [comment]
......yeah that's a lot of overrides to break at this point.

Is there any way to get a pointer to refer to someone's status bar?

**Comment by Accensus** [comment]
Yeah, I think `let HDHud = HDStatusBar(StatusBar);` should work. `StatusBar` is a global variable:
`native ui BaseStatusBar StatusBar;`

**Comment by MatthewTheGlutton** [comment]
I've set up a colour variable that can be used to store the relevant data.

Addding this into the GetSBarNum override will make the indicator white:
`
		let ssbb=HDStatusBar(statusbar);`
`		if(ssbb)ssbb.savedcolour=Font.CR_WHITE;`

**Comment by Accensus** [comment]
I'll check it out in a bit.

**Comment by Accensus** [comment]
Works great. Thanks, Matt!
