### ISSUE TITLE
+NOBLOCKMONST is cleared on monster death.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#198]
Which means that sometimes enemies get stuck within a sector and cannot be pushed off nearby ledges when dead.

**Comment by MatthewTheGlutton** [comment]
Apparently when I was writing that code I thought +noblockmonst meant the opposite of what it meant ("no crossing block monster lines" rather than "not affected by block monster lines").

Should be fixed now.
