### ISSUE TITLE
A way to show items when holding Use but hide them from Invbar.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#199]
Use case: the crafting materials in the universal reloader I'm making shouldn't show up in the inv bar, but there should be a convenient way for the player to check how much they have of them. For the record, they inherit from HDPickup.

It's not really a big deal since one can always use the item manager.

**Comment by MatthewTheGlutton** [comment]
I would've made them ammo so they'd show up on that...

**Comment by Accensus** [comment]
I'll try that and see if I encounter any issues.

**Comment by Accensus** [comment]
Doesn't seem like there's a problem with this approach. Gonna close this.
