### ISSUE TITLE
Icon of Sin head doesn't get killed by crushing floors/ceilings

### ISSUE THREAD

**Issue by CoolBlackYosh** [MatthewTheGlutton/HideousDestructor#200]
There are some maps in the community that make an exit by killing the Icon of Sin head with a crushing platform, in this case, somehow the platforms don't kill it and softlocks you in a map that relies in this type of exit. Example: Map 16 of Freedoom 2 has this type of exit, but you end up getting softlocked due to this issue.

**Comment by MatthewTheGlutton** [comment]
Is this a "proper" bossbrain with the monster cubes or just there as a level-ender? I don't recall it should make a difference but it might.

**Comment by CoolBlackYosh** [comment]
It is only the bossbrain, no cubes/targets, just to finish the map when it gets hurt

**Comment by MatthewTheGlutton** [comment]
Check added, should be fixed. (Tested by summoning bossbrain in the crushers on FD2 map04)

**Comment by CoolBlackYosh** [comment]
Works good, thank you, closing this
