### ISSUE TITLE
Roboball related performance drop

### ISSUE THREAD

**Issue by beatcrazed** [MatthewTheGlutton/HideousDestructor#202]
If you have a roboball get stuck in a teleporter loop, it will keep accelerating and eventually destroy your performance in terms of framerate. This is quite similar to what cyberdemon rockets once did in the same situation, it's probably just bad luck that nobody caught this at the time as well.

You can recreate this situation with [this save](https://drive.google.com/file/d/1htO0GKDq-ahUnV-afjeHRNfC_7lc1hL2/view?usp=sharing) (load with Diabalos Ex and the latest (as of this moment anyway) master.) The save is frozen, so use the freeze console command to get the demonstration started.

Then again, this is so similar to the rockets situation that you probably already know what to change to fix this :P

**Comment by MatthewTheGlutton** [comment]
I sat here for three minutes trying to remember what the Freedoom cyberdemon (assault tripod) was called so I could figure out which .zs file this was. Almost regretting that renaming.

By "roboball" you mean the bfg-like "Satanball", right? (the "Roboball" actor is the rocket.) I've added a time limit to how long it can try to track the target and accelerate towards it - once that limit's hit it just starts meandering randomly instead.

**Comment by beatcrazed** [comment]
I do mean the BFG-like Satanball, I mistakenly thought that one was called the roboball because with the HD debug mode on the console was getting spammed with "Roboball is going over 600 (whatever units) consider using HDbullet instead"

I'll download the new master and see how this goes.

**Comment by beatcrazed** [comment]
Didn't work, but I do have some new data and a new hypothesis: It seems to be either the teleport fog particles or perhaps the teleport dynamic lighting.
![Screenshot_Doom_20200831_185410](https://user-images.githubusercontent.com/22873854/91691403-ace01600-ebbb-11ea-8d8b-b03914052481.png)
![Screenshot_Doom_20200831_185410_01](https://user-images.githubusercontent.com/22873854/91691417-af427000-ebbb-11ea-8139-232068048a17.png)

In these screenshots you can see one set of rockets near the end of their fuel. It wasn't obvious while they were flying straight, but now that they're angling down you can see that they're spawning a lot of teleport fog particles, and (if teleports have them) dynamic lights.

I was also able to get a set of SatanBalls in a loop without any rockets. They no longer cause problems, and maybe never did in the first place.

**Comment by MatthewTheGlutton** [comment]
> Didn't work
> They no longer cause problems

???

**Comment by MatthewTheGlutton** [comment]
Now that I'm no longer in a rush to get out...

That debug message logs the offending actor name. This is in fact the rockets causing the problem.

Does it *eventually* stop at least?

**Comment by beatcrazed** [comment]
Yes, the rockets do eventually stop being a problem when they angle down far enough to hit the ground before being teleported again. This takes far too long to be practical though: One set of rockets is enough to cripple performance, and cyberdemons aren't exactly shy about launching rockets.

As for my last message.

> Didn't work: 

The problem wasn't solved, performance still tanked because of what the cyberdemon was doing.

>They no longer cause problems: 

>I was also able to get a set of SatanBalls in a loop **without any rockets**. They (**the SatanBalls**) no longer cause problems, and maybe never did in the first place.

**Comment by MatthewTheGlutton** [comment]
I think I know what's wrong - the rockets must be so fast they're teleporting many times each tick, resulting in the  massive tfog spam.

Comparing IRL RPGs (300 m/s) and pistol rounds (more than that) I think it's time to put a cap on the rocket acceleration.

**Comment by beatcrazed** [comment]
Oh, I thought it was already capped. That's why my first instinct was that it was the other projectile doing it, even though the console was spamming otherwise :P

**Comment by MatthewTheGlutton** [comment]
It was limited, in that it would eventually run out of fuel and start falling out of the sky.

It's just that until then it would keep adding 10 to its speed every 2 ticks, and that went on 100 times, which added to the starting speed gave us a final speed of 1072 - more than double HD's assumed speed of sound.

Now I'm just going to pretend it's being given just enough thrust to create lift while letting wind drag keep it subsonic, because I don't feel like spawning yet even more actors to create the sonic booms.

**Comment by beatcrazed** [comment]
In the latest master one set of rockets is no longer enough to impact my performance, it takes something more like 8 sets. Definitely an improvement.

**Comment by MatthewTheGlutton** [comment]
Half wondering if I should do anything to cap the telefog spawns...

**Comment by MatthewTheGlutton** [comment]
no weird side effects reported in the past 4 days, no motivation to add a telefog spawn cap without any specific demand for it, I think imma close this one.
