### ISSUE TITLE
Extend ammo boxes to support injection.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#203]
Kind of like ItemsThatUseThis. Perhaps two arrays could be used: item to spawn and how many. Alternatively, expose a function to do that so the modders don't have to access the array directly. Something like `AddAmmoType(string ammo, int amount) { }`

**Comment by MatthewTheGlutton** [comment]
I read "injection" like stimpacks and whatnot and got so terribly confused, lol

No promises but I'll take a look.

**Comment by MatthewTheGlutton** [comment]
Done! Closing this since any followup should be bug reports.
