### ISSUE TITLE
Dev build of GZDoom aborts on loading Hid Dest

### ISSUE THREAD

**Issue by physixcat** [MatthewTheGlutton/HideousDestructor#204]
I'm noticing that on a freshly compiled build from the master branch of GZDoom, I'm getting this error upon loading the master branch of Hideous Destructor

```
gzdoom: gzdoom_build/gzdoom/src/common/scripting/backend/codegen.cpp:1846: virtual ExpEmit FxMinusSign::Emit(VMFunctionBuilder*): Assertion `ValueType == Operand->ValueType' failed.
Aborted
```

Can anyone else confirm this happens to them as well on the GZD dev build? It's g4.5pre-149-gec3cd68c1

**Comment by nicothegoat** [comment]
the debug build has a bunch of failing asserts for some reason
compile a release build instead ( add `-DCMAKE_BUILD_TYPE=Release` when generating build files )

**Comment by MatthewTheGlutton** [comment]
I don't think there's anything I can or ought to do on my end so I'll close this.
