### ISSUE TITLE
Failure to switch to bandages on incap.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#205]
Jump to the range, give yourself some spiritual armor, equip any gun, summon a zombieman, and let him shoot you. You won't switch to banages when you drop to the floor. Happens with the fists, too.

**Comment by MatthewTheGlutton** [comment]
Is it only with spiritual armour? Trying buddha mode works fine so far.

**Comment by MatthewTheGlutton** [comment]
Apparently player.cmd.buttons is now this huge 33 million something number instead of zero when there's no input.

I've changed it to check for specific buttons instead, though this might be a GZDoom bug.

**Comment by MatthewTheGlutton** [comment]
GZDoom bug reported though the fix on HD's side should work with either dev or 4.4.2.
https://forum.zdoom.org/viewtopic.php?f=2&t=70091
