### ISSUE TITLE
Don't start with Zandronum 

### ISSUE THREAD

**Issue by miosaurio** [MatthewTheGlutton/HideousDestructor#208]
![image](https://user-images.githubusercontent.com/38572750/96415972-f65ce280-11b4-11eb-9657-3b34f35c9be6.png)

**Comment by Accensus** [comment]
From the Discord:
> The "Zandronum-compatible" version of Hideous Destructor linked in the forum thread is from 2012. It is not officially supported, has next to nothing in common with modern HD, and you will not receive any support for it. 
Modern Hideous Destructor has no chance of working in Zandronum, and all multiplayer is played using GZDoom, and not Zandronum.

**Comment by miosaurio** [comment]
> From the Discord:
> 
> > The "Zandronum-compatible" version of Hideous Destructor linked in the forum thread is from 2012. It is not officially supported, has next to nothing in common with modern HD, and you will not receive any support for it.
> > Modern Hideous Destructor has no chance of working in Zandronum, and all multiplayer is played using GZDoom, and not Zandronum.

thanks .
