### ISSUE TITLE
"Spawn multiplayer weapons" option is not respected

### ISSUE THREAD

**Issue by FinalStaticFox** [MatthewTheGlutton/HideousDestructor#27]
I've been trying to set up a multiplayer game to play with a friend, using the latest release (3.7.1.0). However, no matter the state of sv_noweaponspawn or how many times I restart/change maps, HD will spawn the multiplayer weapons in coop games.

I've been trying to make it work for a few hours, desperately trying to figure out what I was doing wrong, until I started a vanilla doom game and saw that I did set things up correctly...

**Comment by MatthewTheGlutton** [comment]
t(°▿°)-

l(°.°)-

...I have no idea what point that's even checked, and haven't given this issue any thought in years. Will take a look.

**Comment by MatthewTheGlutton** [comment]
For what it's worth, I'd given up on this all those years ago for the reasons mentioned here: https://github.com/SamsaraDevs/samsaraJunk/issues/94

**Comment by MatthewTheGlutton** [comment]
Apparently copypasting this https://github.com/coelckers/gzdoom/blob/1a633701b3bcee352b5c03c21203ca4ecd7cac97/src/p_mobj.cpp#L5379 is not going to work all on its own.

Does anyone know how I can get an actor's spawn flags?

**Comment by MatthewTheGlutton** [comment]
Fixed as of f585234e9f9ac6aa4fba8c42c93b93906a04c35e

**Comment by FinalStaticFox** [comment]
Okay, I just downloaded the latest master (42a043efc0bc379b5a0ca1a2d202e5c1cf56884b) to test it out and there's a few really weird problems :

First, if I start a host game with "+sv_noweaponspawn 1" in the command line, once in game none of the players can look around, their aim is locked in the same direction as if they were changing the zoom on their sight (ie: the screen shake when you move the mouse, but you always end up looking at the same spot)
Changing sv_noweaponspawn once the game is launched bypass this issue, but it comes with it's own set of problems. If you did not hold the medpack or steampack "weapons" at least once beforehand, you won't be able to use those. The medpack items will just disappear when using them and using the stimpack items won't do anything at all. Also, HERPs will disappear on pickup no matter what.

**Comment by MatthewTheGlutton** [comment]
Okay, so I wasn't imagining things that one time the tripwires weren't working.

Will take another look.

**Comment by MatthewTheGlutton** [comment]
Fixed in a non-stupid way as of 9df78052b86f7a5a6b3c6a969b9527d5d624dd7a

**Comment by FinalStaticFox** [comment]
Just tried it out and it seems to be working fine. Thank you!
