### ISSUE TITLE
Derp setting in remote control never changes via console command

### ISSUE THREAD

**Issue by ElonSatoshi** [MatthewTheGlutton/HideousDestructor#29]
How to reproduce:

1. Drop a derp. Open the derp remote control. Set the derp's mode to 2

2. Switch to another weapon. Open the console and type `dp` to set the derp's mode to 3, or patrol

3. Open the derp remote control again.

Expected result:

The derp remote should show the derp in mode 3. The derp should continue patrolling.

Actual result:

The derp stops moving as soon as you open the remote. The remote shows the derp's mode as 2

I have confirmed this in both v3.7.1.0 and commit 08deb1685bb54e4eb8442878903e844bc08fc8f3

I can't think of a better title for this issue.

**Comment by MatthewTheGlutton** [comment]
Fixed in 16a9cb817bf1465ac451bdd88650f231e11f5ea5
