### ISSUE TITLE
GZDoom hard crash when enabling NiteVis

### ISSUE THREAD

**Issue by caligari87** [MatthewTheGlutton/HideousDestructor#35]
To reproduce (at least for me) start Infiltrator on Doom2 MAP01 and enable the nightvision goggles. My GZDoom hard-crashes instantly with the following error:
```
GZDoom g4.0.0 - 2019-04-07 09:11:51 +0200 - SDL version
Compiled on Apr  8 2019

////----snip----////

Starting Loadout: Infiltrator


*** Fatal Error ***
Address not mapped to object (signal 11)
Address: (nil)

Generating gzdoom-crash.log and killing process 4695, please wait... 30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
sh: 1: gxmessage: not found
```
Running Linux Mint 18.2 Cinnamon.

I have bisected the problem back to commit 90e48fab8854ec05370985937449d6e69313f6a8, so I presume this has something to do with the nightvision visor dynamic light change referenced in that commit. I have not tested anything else that might have broken similarly.

**Comment by MatthewTheGlutton** [comment]
As discussed on Discord, I've posted this to the GZDoom bugs forum since this should have just resulted in a VM crash not a CTD. https://forum.zdoom.org/viewtopic.php?f=2&t=64307
