### ISSUE TITLE
Liberator always spawns with GL in new game

### ISSUE THREAD

**Issue by Nisteth** [MatthewTheGlutton/HideousDestructor#38]
If you make a loadout to spawn with a liberator (classic or bullpup, doesn't matter) without the grenade launcher attachment, it instead gives you one *with* the attachment. This makes it impossible to spawn with a liberator without a grenade launcher.

**Comment by Nisteth** [comment]
ADDENDUM: This actually seems to do something somewhat worse - every liberator code, regardless of purpose, will instead give a bullpup liberator with a GL. Even the classic variants will, instead, give a bullpup.

**Comment by MatthewTheGlutton** [comment]
I'm in the middle of a total overhaul of how all this stuff works. Right now only the new method works, which is to define some parameters in the loadout, e.g.:
```lib nogl nobp```
to give a non-bullpup Liberator with no grenade launcher.
