### ISSUE TITLE
Medikit thinks imp is a serpentipede

### ISSUE THREAD

**Issue by ElonSatoshi** [MatthewTheGlutton/HideousDestructor#40]
How to reproduce bug:

1. Load Hideous Destructor in GZDoom, select Doom or Doom 2 as the IWAD

2. Find an imp

3. Open a medikit

4. Walk up to the imp

5. Hold firemode and click altfire.

**Comment by boogiebogus** [comment]
the imp's actor name is serpentipede, which is what the medikit returns, so i wouldn't say this is a problem

**Comment by MatthewTheGlutton** [comment]
I was gonna say the same thing, but now that all the HD monsters are consolidated I think we can work around this with a "nicename" variable similar to inventory items.

Closing this since it'll be a generalized improvement rather than addressing this issue specifically.
