### ISSUE TITLE
Feature request: Weaponized medical supplies, thrown objects

### ISSUE THREAD

**Issue by ElonSatoshi** [MatthewTheGlutton/HideousDestructor#41]
Are you a naturist that somehow accidentally wandered into Hell, and you're surrounded by imps, but the only thing you can find that might be useful is a stimpack and a medikit? Wouldn't it be neat if you could inject 2 or 3 stimpacks into your enemy, or inject Second Flesh into them to distract them with pain? I just realized even some unnecessary stables and Bio-Foam injections could be a bit distracting to a demon.

I think it would also come in handy to be able to throw objects and have them hurt enemies when said thrown object hits them, perhaps by holding zoom + drop item to throw inventory items with force, or zoom + drop weapon to throw magazines with force from the magazine manager. And thrown weapons should hurt enemies as well, they should hurt even more than thrown objects, perhaps enough to even kill an imp/soldier since many of them are somewhat heavy objects.

**Comment by ElonSatoshi** [comment]
well that sucks

**Comment by scrumbo** [comment]
Elon, I can't make any promises (having never modding before,) but _if_ somewhere down the line I _might_ learn to make a "how-to" or templates for addons like this.

That is, if you or someone else doesn't beat me to it first.
Not asking anyone to do this, but I'm down for any resources to learn from, besides just fumbling around like I have been doing.
