### ISSUE TITLE
Lift limit on amount of loose 4.26mm rounds you can store in your inventory.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#44]
Changed it locally to 5000 for testing purposes. Seems to work just fine. Is there a particular reason behind why it's 300?

**Comment by MatthewTheGlutton** [comment]
It spontaneously combusts at random when you try to stick it in the mag.

I'll consider actually replicating that consequence instead of presuming the player will always avoid it.

**Comment by MatthewTheGlutton** [comment]
added in 727fb483fa1e0511d3b33797474beafa3b2dad5c
