### ISSUE TITLE
Add backpack max bulk multiplier (or absolute value slider).

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#45]
1000 is just perfect for the Hardcore preset with 1.0 encumbrance, but with 0.25 encumbrance you can essentially fit 5+ backpacks worth of ammo in your pockets, yet only carry 1 on your back. Would be nice to have the ability to increase the max bulk. Mainly for all of us hoarders out there.

**Comment by MatthewTheGlutton** [comment]
On the one hand, I have no desire to enable this kind of hoarding behaviour.

On the other, the inconsistent treatment actually bothers me.

Added in 63f14edfd48597a8dcc9c73390352bdca5c2f809.

**Comment by Accensus** [comment]
Thanks.

I agree that hoarding is bad, but if someone is playing with <1.0 encumbrance I have to assume they aren't really bothered by it in the first place. I'd argue that hoarding has the benefit of making the player  more creative in their ways to haul their stuffed backpack from one side of the map to another. It's quite fun, actually, especially if you have a ladder.
