### ISSUE TITLE
VM Abort with Serpentipede

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#49]
![Screenshot_Doom_20200106_160911](https://user-images.githubusercontent.com/24256978/71823151-3d06a380-309f-11ea-82fc-629c4b96409d.png)

Wasn't doing anything special, just shooting imps.

**Comment by MatthewTheGlutton** [comment]
Fixed in 4f7086cf44687db38b1a70b577609e0e7b7873c1

That it took this long for anyone to catch probably says something about how often these fireballs hit anything at all...
