### ISSUE TITLE
Prevent auto-management of magazines in backpack

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#50]
The mechanic replaced 15 full SMG mags in my inventory with 15 empty mags from the backpack and I got shot in the face when I failed to reload. This smells like a bug, but an option to turn off auto-management completely would be appreciated. I tend to make a specific setup at the end of each map and having to do it over again the next one is somewhat of a bummer. Can't always do it at the start of a map because of hostiles.

**Comment by MatthewTheGlutton** [comment]
Give me a moment to consider this as I'm considering removing this function entirely instead of making it yet another cvar.

**Comment by Accensus** [comment]
Take your time. Thanks for looking into it.

**Comment by MatthewTheGlutton** [comment]
After looking at the code I think I'm going to address this with a single option whether to do automatic inventory consolidation between levels.

Before this, though, I need to make sure all that stuff can be done during play so people who enable such an option aren't permanently hindered.

Fortunately the only thing is robot repair. HERP is done as of last night, but DERP needs a long-overdue overhaul...

**Comment by MatthewTheGlutton** [comment]
Done.

**Comment by Accensus** [comment]
Awesome. Thanks!
