### ISSUE TITLE
Add icon to HDFragGrenades

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#51]
War Trophies utilizes the icon property first and falls back to spawn state frames if one doesn't exist. In the case of grenades, neither work because the states are TNT1A0 and there's no icon.

**Comment by MatthewTheGlutton** [comment]
Just to clarify, we're talking about the weapon, right? not the ammo?

**Comment by Accensus** [comment]
Yep, the weapon. Adding an icon to `class HDFragGrenades:HDGrenadethrower` on my end made the icon show up.

**Comment by MatthewTheGlutton** [comment]
Addressed in 4c8c5a61294d32269e7d5cd5480f44740b28eaff
