### ISSUE TITLE
Strange sound when killing certain enemies at a distance.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#53]
Hard to explain what it sounds like. Try it at the range. Spawn a pain elemental at about 30m and shoot it with the ZM66 or any other weapon. I personally tested it with the ZM66. Got a feeling this has something to do with the recent DistantNoise refactor.

EDIT: Doesn't happen with 4.2.4b.

**Comment by boogiebogus** [comment]
can confirm on my end too.

it made a fart noise which is hilarious

**Comment by MatthewTheGlutton** [comment]
Only seems to happen in Doom2 not Freedoom...

**Comment by MatthewTheGlutton** [comment]
That is apparently what the fire crackle sound (which is still missing in FD) sounds like at pitch of 3.0 because of a typo.

Fixed.
