### ISSUE TITLE
Pickups are infinitely tall if you're above them.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#54]
Easily tested on the range. Spawn a weapon or whatever next to the boxes where the ladder is, climb the ladder, and pick up the item. You can pick it up even if it's way down there.

**Comment by MatthewTheGlutton** [comment]
Did something change with GZDoom's collisions? I remember testing this a long time ago.

Added an explicit Z position check to the antenna.
