### ISSUE TITLE
Discrepancy in weapon ammo meter.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#55]
Go to range, pick up ZM66, shoot a few times, hold Use. The ammo meter will be a bit longer than if you're not pressing Use. If it doesn't happen at first, shoot a few times and try again. This was tested on 1920x1080 with a Fullscreen HUD scale of 3.

**Comment by caligari87** [comment]
The ammo bar is semi-randomly inaccurate normally, but becomes perfectly accurate if you hold `use`. This can be seen with pretty much every gun that uses it I believe

**Comment by MatthewTheGlutton** [comment]
What Cali said.
