### ISSUE TITLE
Slightly increase uninjured crawling speed.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#56]
When I think about it, it makes little sense that you aren't be able to crawl relatively fast if you're not injured (and not carrying an entire gun store on your back). Perhaps the speed could be increased by about 40% if you're near perfect condition? I watched a few vids of soldiers crawling under barbed wire in the mud, just to get a sense of how fast a person can crawl in the first place, and they sure moved quickly.

**Comment by boogiebogus** [comment]
i mean, you're not prone, you're playing dead. presumably you're shuffling around as slowly as possible.

**Comment by Accensus** [comment]
That does make sense, but only in multiplayer. There's not much point in shuffling around slowly while getting shot in singleplayer. Unless you're not supposed to use the feature in SP.

**Comment by boogiebogus** [comment]
i mean, the only real point of it in singleplayer is to get under super short gaps where speed is probably not a problem

tip: you can leave playing dead as soon as your hitbox gets under the gap to go through much faster

**Comment by Accensus** [comment]
Ah, I see. Thanks for the tip, I'll keep it in mind. I suppose this can be closed then.
