### ISSUE TITLE
ZM66s can be converted from semi-auto to full-auto.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#58]
A video speaks a thousand words. See below. Ammo in the magazine is also affected by this. Haven't tested with map-placed weapons, just ones dropped by enemies. Doesn't seem to happen with the Hunter.

https://cdn.discordapp.com/attachments/425904160970506251/665894199534813194/2020-01-12_14-24-35.mp4 (Will download the vid)

EDIT: Depending on the drop order, you can instead turn all full-autos into semi-autos.

**Comment by MatthewTheGlutton** [comment]
I'd rather you explained the exact steps which would take a lot less than a thousand words... I can't figure out what's going on in that video at all

**Comment by Accensus** [comment]
Alright then. You'd need to find 3 ZM66s dropped by zombiemen. Technically none of them need to be semi-auto, but it helps visually when you drop them. Pick up all 3. Drop them in whatever sequence. First weapon will be unaffected. However, the 3rd dropped weapon will mimic the 2nd. So basically the last 2 dropped weapons will be identical, both in terms of ammo in mag and selective fire. I only cycled the weapons in the vid so you can look at the ammo and memorize the numbers. It's nothing special and it's really easy to replicate, not really pressing any keys other than cycle stack and drop weapon. I feel that it has something to do with weapon cycling.

**Comment by MatthewTheGlutton** [comment]
Got it. Will take a look.

**Comment by MatthewTheGlutton** [comment]
Fixed in e17eca279cfa34717de9305b20afdcca2f4b88cd
