### ISSUE TITLE
Spamming "bring up lowest mag" in mag manager doesn't always (?) sort mags.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#59]
Not even sure if it's supposed to do it in the first place. If I have one empty mag and another with, say, 5 rounds, it will move the 5 rounds one to the top and swap between empty and that. If I have two mags with 0 rounds and some other half-full mag, it will only swap between the empty ones. Even if I have a third mag like in the pic (10 rounds), it will not move it closer to the top. Intentional?

![Screenshot_Doom_20200113_170528](https://user-images.githubusercontent.com/24256978/72266668-7d2dcf00-3627-11ea-9171-aa7d8e5a079a.png)

**Comment by MatthewTheGlutton** [comment]
As of 4.2.4a: "Magazine manager select-lowest now selects only the lowest mag that is not currently selected."

Not the most intuitive when it comes to predicting where each mag ends up going after multiple presses, but it seems to be a bit more convenient for ordinary use.
