### ISSUE TITLE
Stripping armor while carrying a spare set of armor in creates false double

### ISSUE THREAD

**Issue by Fallingferret** [MatthewTheGlutton/HideousDestructor#6]
pretty simple to reproduce. hit your strip key while you've got a spare sitting in your inventory and you end up spitting out two of your currently equipped armor set onto the floor. only one of them will actually back into your inventory, while the other will just vanish after making the pickup sound.

slightly distracting, but fun in your down time
![screenshot_doom_20180323_002629](https://user-images.githubusercontent.com/19625046/37816642-14508d06-2e31-11e8-9008-c5deb6bdef40.png)

**Comment by MatthewTheGlutton** [comment]
Can't reproduce. Please provide the EXACT steps taken.

**Comment by MatthewTheGlutton** [comment]
Oh, right, I think I remember that now! Thanks for checking anyway!

**Comment by MatthewTheGlutton** [comment]
That fix was just a half-self-educated guess that GoAwayAndDie had weird side effects! Glad to know it worked...
