### ISSUE TITLE
Make "Prevent weapons from destroying map" option not affect Door Buster.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#61]
Technically it's not a weapon, and you don't accidentally attach and detonate a Door Buster. This is for people who want to bust geometry only via the necessary equipment (i.e. door buster). I'm currently playing through a map where you could accidentally shoot off the legs of a desk (there's a *lot* of desks here) with weapons and it's a real immersion breaker, especially when they explode. But I'd still like to retain the ability to bust doors with the right tools.

**Comment by MatthewTheGlutton** [comment]
Addressed in bd574d9af7fde693b6c3d68640f62ce2b61f9941

Limiting it to *only* the doorbuster would be too arbitrary and gamey, so option 2 will still allow the most obvious destroyers to function.
