### ISSUE TITLE
Fix hd_nodoorbuster using the wrong OptionValue in MENUDEF.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#62]
https://github.com/MatthewTheGlutton/HideousDestructor/blob/647d70541911a45e68a0eb9df57438b16ea985d0/menudef.txt#L35

Should be `DoorBuster`. Otherwise it shows up as Unknown in menu.

**Comment by MatthewTheGlutton** [comment]
fixed
