### ISSUE TITLE
Size discrepancy between full and partial 7.76 mags

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#64]
![Untitled](https://user-images.githubusercontent.com/24256978/72803007-aff24b80-3c55-11ea-98d2-a4be61847f95.png)

Left is full, right is partial.

**Comment by Accensus** [comment]
Apparently this might be a user error. I don't know why I got the impression these mags were from HD and not the skin pack I'm using. Huh.

**Comment by Accensus** [comment]
Well, the size discrepancy is still there even in vanilla HD, it's just more noticeable in the skin pack.

**Comment by MatthewTheGlutton** [comment]
Is this only in the HUD or are the world sprites a problem as well?

**Comment by Accensus** [comment]
Only the HUD it seems.

**Comment by MatthewTheGlutton** [comment]
Addressed in bff6cf1
