### ISSUE TITLE
Backpack always shows 1 autoreloader on person, even if you have more.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#65]
I have 3 in inventory, as seen in the screenshot.

![Screenshot_Doom_20200122_125746](https://user-images.githubusercontent.com/24256978/72888820-02e00780-3d17-11ea-8d01-59cef48849b6.png)

**Comment by MatthewTheGlutton** [comment]
Fixed in 423646babe876b033ac32b647f5362a2482b54eb
