### ISSUE TITLE
Taking out additional autoreloaders from the backpack drops them

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#66]
Only happens if you already have an autoreloader in your inventory. Might be related to #65.

**Comment by MatthewTheGlutton** [comment]
Also happens with all items that are based on HDWeapon, though the code for it is unrelated.

It will be a bit more involved to fix than the other one.

**Comment by MatthewTheGlutton** [comment]
Addressed in 72f0de8a0028c7fbcbe0c9f92bbd90b3dd45d27a
