### ISSUE TITLE
Make medikits able to inject 2f into treated wounds

### ISSUE THREAD

**Issue by boogiebogus** [MatthewTheGlutton/HideousDestructor#68]
I don't really see why not.

On top of that, perhaps change the medikit up a little, so that the amount of treated wounds that you normally heal is less so you'd have to use it on treated wounds more often.

**Comment by MatthewTheGlutton** [comment]
I just tried giving myself 10 wound points, bandaging them, then using the 2F. It can deal with the bandaged wounds just the same as unbanaged ones.

What do you mean by "treated"?

**Comment by MatthewTheGlutton** [comment]
It has been explained on the discord that this is about "oldwoundcount".

I'll take another look at what all these numbers are even supposed to mean before I can commit to a yes or no...

**Comment by MatthewTheGlutton** [comment]
Confirmed "oldwoundcount" is still healing/scarring tissue where the wounds have already been closed.

To 2F that you'd need to cut open the wound again, which would lead to complications that aren't modeled in HD.

Might revisit the concept later but it's a [No.] for now.
