### ISSUE TITLE
DERP eats pistol magazine after expending all ammo

### ISSUE THREAD

**Issue by TwelveEyes** [MatthewTheGlutton/HideousDestructor#71]
After picking up a DERP that has fired all its bullets it is no longer possible to unload the empty mag from it.

**Comment by MatthewTheGlutton** [comment]
Works fine for me.

I deployed a DERP on the firing range, then kept summoning zombiemen next to it (keeping my gun pointed at each one and making sure none of them ever got a shot at the DERP) until it stopped attacking them, then picked it back up. Showed ammo count of 0, hit reload, showed no mag, switched to magmanager, found an empty mag.

Are there any other steps to replicate this?

**Comment by TwelveEyes** [comment]
I'm probably mistaken as I can't reproduce it. I might have just hit unload on a DERP without realizing it and losing a mag.
