### ISSUE TITLE
Wall decals for blood completely missing

### ISSUE THREAD

**Issue by TwelveEyes** [MatthewTheGlutton/HideousDestructor#72]
I'm unsure if this is a deliberate stylistic choice or a issue, but blood decals do not show up.

A hack that could be implemented would be putting "A_SprayDecal(random(0,1)?"BloodSplat":"BloodSmear",172);" in postbeginplay() of HDMasterBlood, but that doesn't take into account actor bloodcolor; it will always default to red.

**Comment by boogiebogus** [comment]
I'm personally not experiencing this issue.

**Comment by TwelveEyes** [comment]
Really? You're not using any blood replacement mods are you?

**Comment by boogiebogus** [comment]
disregard that i am, but only with bullet weapons

oddly enough the chainsaw isn't affected

**Comment by MatthewTheGlutton** [comment]
Last I checked getting blood colour for decals was buried somewhere in an actor's hard-coded damage routines.

Tempted to make everything bleed red since that's already canon in Freedoom anyway...

**Comment by MatthewTheGlutton** [comment]
TIL "TraceBleed" is a thing

Hopefully this is the last thing I fix before a new stable can come out

**Comment by MatthewTheGlutton** [comment]
Done!

If you don't see the splatter, it's not penetrating enough.
