### ISSUE TITLE
Setting hd_nv to 999 then back to a different value permanently forces fullbright.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#77]
What says in the title. I tried it with 999 and 5. Exact steps to reproduce:
1. Set hd_nv to 999
2. Turn on NV
3. Set hd_nv to 5
4. Turn off NV
Everything would be fullbright.

**Comment by MatthewTheGlutton** [comment]
Does GZDoom even run on anything that can't use the shader anymore? If not I'd like to remove the fullbright option.

**Comment by MatthewTheGlutton** [comment]
Addressed in 180273c6ca6c029e76cd4d0f2e0e9a0a47ba5985
