### ISSUE TITLE
Probable error in shield damaging

### ISSUE THREAD

**Issue by boogiebogus** [MatthewTheGlutton/HideousDestructor#78]
starting at line 131 of mobdamage.zs:

			if(damage<1){
				if(
					!(flags&DMG_NO_PAIN)
					&&blocked>(sphlth>>2)
					&&random(0,255)<painchance
				)forcepain(self);
				return -1;
			}

This would mean that only attacks that deal 0 damage can flinch, which makes no sense.

**Comment by MatthewTheGlutton** [comment]
This is only called when the shields reduce damage to 0 or less.
If there's still any damage remaining, this is not called and the regular damage code is applied to that remaining damage.
