### ISSUE TITLE
Allow smoother/slower airburst adjustment.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#79]
At least in the 10-100 range. In the middle of a firefight it's a bit troublesome to get the airburst right and usually the grenade explodes either too soon or too late. Or I get shot in the face if I take too long to find the right number. But even behind cover it's still a bit finicky to get it right.

**Comment by MatthewTheGlutton** [comment]
Not sure how to fix this without making things worse elsewhere.

Is the `ab` command at all useful?

**Comment by Accensus** [comment]
I didn't know that was a thing/had forgotten about it. Works great for me, as long as I don't have to fiddle with the mouse. Thanks!

**Comment by MatthewTheGlutton** [comment]
Would slowing down the scroll method be helpful anyway?

My original idea was something like, use the scroll method for longer distances and use `ab` for fine-tuning, but that doesn't really seem to make sense (esp. given someone might be using this with `rf` at longer distances and--

::actually tries it::

....yikes that's fast. Slowing it down now.

**Comment by caligari87** [comment]
I noted in the discord, but just about everything that uses mouse-movement scrolling is super-sensitive and could probably stand to be reduced by a significant factor.

**Comment by Accensus** [comment]
I just tested this and it seems to actually be worse because the speed threshold for setting the airburst feels much higher, meaning I have to move the mouse faster for it to trigger, but once it kicks in it changes too fast because I'm moving so fast.

**Comment by Accensus** [comment]
Also movement in the other direction doesn't have that threshold, which is mildly inconvenient. My suggestion would be to only lower the threshold needed to increase airburst and bump the one for reducing it. I think that'd work.

**Comment by MatthewTheGlutton** [comment]
Added a bunch more calculations.

The movement should be symmetrical but abs() is a thing I routinely forget to add.

**Comment by Accensus** [comment]
As Duke would say: "Ahhhhhh, much better."
Thanks, Matt!
