### ISSUE TITLE
manual gives invalid derp commands

### ISSUE THREAD

**Issue by evenex** [MatthewTheGlutton/HideousDestructor#8]
several commands listed beginning at hd_manual.txt:521 don't work, including

`derpccome`
`derp 123`
`derp 555`

I'm not clear on what `<tag>` refers to but giving arbitrary ints as a 2nd arg to `derp` also doesn't work

When the commands are attempted in GZdoom with HD-3.2.5.3, I get the list of valid derp commands

**Comment by MatthewTheGlutton** [comment]
Why are you using the current manual for an old version?
