### ISSUE TITLE
Manage non-mag ammo with mag manager

### ISSUE THREAD

**Issue by TwelveEyes** [MatthewTheGlutton/HideousDestructor#80]
Allowing the player to manage shells, rocket grenades, grenades, heat rockets, etc. with the mag manager would allow ammo management to be less cumbersome, and wouldn't require players to pick up a backpack for that functionality.

**Comment by Accensus** [comment]
What? How would you even manage those?

**Comment by TwelveEyes** [comment]
Would allow you to drop ammo individually, like with the backpack. Instead of managing ammo for weapons you don't have going "purge ammo onto floor, try and pick up what you want, mess up cause the antenna touched something you didn't mean to pick up, purge ammo again and start over".

**Comment by Accensus** [comment]
`hd_dropone` doesn't work?

**Comment by MatthewTheGlutton** [comment]
Not if you don't have a weapon of that type.

The entire interface is built on the assumption that if you don't have the weapon for that ammo type you don't really care beyond making sure it's not encumbering.

I have no idea how much needs to be changed to get a suggestion like this to work...

**Comment by TwelveEyes** [comment]
Can't do `hd_dropone` if you only have the ammo and no weapon that uses it. Also it's a little unintuitive to use `hd_dropone` with a zm66/lib w/gl to get rid of a rocket grenade and have to pick up the mag dropped too.

**Comment by MatthewTheGlutton** [comment]
I was going to suggest the normal drop command which should work, but I never remember the actor names and I code this thing...

**Comment by MatthewTheGlutton** [comment]
I've added a separate pickup manager. Hit the mag manager key while in the mag manager to switch, same key switches back.
