### ISSUE TITLE
Frag grenade tripwire placed on map doesn't attach to sectors

### ISSUE THREAD

**Issue by nicothegoat** [MatthewTheGlutton/HideousDestructor#84]
Both the grenade and the gum wad fail to find a sector to attach to.

[Map demonstrating this bug](https://github.com/MatthewTheGlutton/HideousDestructor/files/4142731/tripwire.zip)

**Comment by MatthewTheGlutton** [comment]
Should be fixed in cefc9e2a222d7a4546a3c7d71dd24d4dc20e46c9

**Comment by nicothegoat** [comment]
The grenade itself still doesn't attach to its sector.

**Comment by MatthewTheGlutton** [comment]
...right, the grenade as well.

**Comment by MatthewTheGlutton** [comment]
[tripwire-bothways.wad.zip](https://github.com/MatthewTheGlutton/HideousDestructor/files/4143164/tripwire-bothways.wad.zip)
Confirmed it works both ways now.
