### ISSUE TITLE
hd_strip does nothing with just a backpack

### ISSUE THREAD

**Issue by boogiebogus** [MatthewTheGlutton/HideousDestructor#87]
It would probably make sense for hd_strip to remove the backpack if you're wearing that and nothing else. Note that this is without any armor in your inventory.

**Comment by MatthewTheGlutton** [comment]
Should be same with radsuit, since like I mentioned on the other issue hd_strip is just an alias to use/drop armour.

**Comment by MatthewTheGlutton** [comment]
I momentarily misread the title as "jetpack" instead of "backpack".

Adding this comment to remind myself  that that needs to be addressed as well.

**Comment by MatthewTheGlutton** [comment]
I thought the end result would simplify things.

It does not.

It does address this issue at least.
