### ISSUE TITLE
Rearrange weapon priority when using scroll wheel.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#89]
Right now the order for the slot 6+ weapons is Thunder Buster -> Liberator -> BFG -> Brontornis when using scroll wheel. 95% of the time, TB is not what you'd want to select when you switch from, say, the shotgun slot. And if by some chance it is what you want to select, you usually have the time to go through the other weapons or use the slot key.

The priority is fine when using the slot keys directly, i.e. Liberator is before TB, but those are sometimes slower to use than just using the wheel if I know that the weapon I'm looking for is just one weapon away in whatever direction. If your setup is SMG, TB, Lib, you're outta luck if you want to quickly switch from SMG to Lib. Personally, using the keys means I'd have to limit my mobility because I have to let go of one of the movement keys in order to reach out and press the required key.

**Comment by MatthewTheGlutton** [comment]
I have no idea how to do this.

**Comment by Accensus** [comment]
Actually, scroll wheel is just what I've bound to the Prev/Next Weapon commands. This can likely be done via overriding PickNextWeapon() and PickPrevWeapon() on the player, since those are called whenever the commands are used.

**Comment by MatthewTheGlutton** [comment]
I know that there's a weapon.selectionorder property that has something to do with priorities, but as far as weaponslots are concerned it's always ignored in favour of prioritizing whatever weapon is last defined...

**Comment by MatthewTheGlutton** [comment]
Thunder Buster -> Liberator -> BFG -> Brontornis
The selectionorder numbers for these are, respectively, 70, 27, 91, 60.
Which as far as I can tell follows no pattern whatsoever.

They are, however, the load order in the ZS includes: TB, Liberator, BFG, Brontornis.

This is the reverse of the slots but obviously one can just scroll the other way.

Can you see if the updated zscript.txt arranges things in a saner way?

**Comment by Accensus** [comment]
Well, it fixed the Prev/Next weapon problem, but inverted the direct slot selection, so now TB is selected first. I think `Weapon.SlotPriority` might be what's needed.

**Comment by MatthewTheGlutton** [comment]
That is absolutely fucked the fuck up... this arrangement works as predicted, later weapon first, for all slots except 6 and 7.

I'll try this SlotPriority later.

**Comment by MatthewTheGlutton** [comment]
Confirmed SlotPriority works for pistols! Will be updating things in a bit.

But first to completely rewrite that awful wiki description...

**Comment by MatthewTheGlutton** [comment]
And I think that's all the slot-selectable weapons.

Everything is just 1, 2, 3, etc. and modders with in-between weapons can set 1.5, etc..

I have no idea if the original issue is currently correctly addressed.

**Comment by Accensus** [comment]
Nope. We're actually back to the original issue as reported. I'm starting to doubt the fixability of this.

**Comment by MatthewTheGlutton** [comment]
Is it currently going through all the weapons in each slot before going on to the next?

**Comment by Accensus** [comment]
Yeah. That's expected, though. Issue is which weapon is the first one in the slot.
Order using key: `Revolver -> Pistol -> SMG -> Slayer -> Hunter -> ZM66 -> Vulcanette -> GL -> RL -> Lib -> TB -> Bronto -> BFG -> Boss`
Order using scroll wheel (starting from Fist): `SMG -> Pistol -> Revolver -> Hunter -> Slayer -> Vulcanette -> ZM66 -> RL -> GL -> TB -> Lib -> BFG -> Bronto -> Boss`

**Comment by MatthewTheGlutton** [comment]
I think I'll have to leave it as it is, since presumably some of the problem can be mitigated by scrolling in the opposite direction while using the slot keys can only go one way.

**Comment by Accensus** [comment]
Fine by me. Thanks for trying at least. Is appreciated.
