### ISSUE TITLE
Use mod-defined fonts or add HUD font colors.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#91]
Some maps(ets) define their own fonts, and using those makes some parts of the HUD quite difficult to see. See below. Alternatively, an option to change the color of the numbers would also work so there's at least some sort of contrast.

Example:
![Screenshot_Doom_20200207_124438](https://user-images.githubusercontent.com/24256978/74023167-a6801780-49a7-11ea-8543-5ddba7e3f568.png)

**Comment by MatthewTheGlutton** [comment]
Changed them all from black to olive... any better?

**Comment by Accensus** [comment]
Only a little bit. Still hard to see. Might need a brighter color.
![Screenshot_Doom_20200208_082918](https://user-images.githubusercontent.com/24256978/74080493-3035f080-4a4d-11ea-8568-1024ba8ce099.png)

**Comment by MatthewTheGlutton** [comment]
what the fuck

I can't fix this, it is the mod's fault

**Comment by Accensus** [comment]
Well it's not a big deal to just crack open the mapset in SLADE and nuke the fonts, so no worries.

**Comment by MatthewTheGlutton** [comment]
I might reconsider this in the future and just use, like, newsmallfont or something that is unlikely to be replaced by a pwad.

**Comment by Accensus** [comment]
Tested the commit with the newsmallfont edit. Works great. Cheers, bud! I'm only not sure about the color. Grey was better imo (the font itself was problematic), but I'll leave it up to you.

**Comment by MatthewTheGlutton** [comment]
I'll stick with olive for now since that's the starting default and also most ammo items are dark-ish grey themselves so a bit of hue helps the number stand out.
