### ISSUE TITLE
More invalid sound position.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#93]
Not sure what caused it. Happened when I threw an empty pistol mag, but I somehow doubt it's related.
![Screenshot_Doom_20200209_171747](https://user-images.githubusercontent.com/24256978/74104738-4a142800-4b60-11ea-8efb-ad502e3639c9.png)

**Comment by MatthewTheGlutton** [comment]
Were there revenants anywhere on that map previously? It's not a NaN, just extremely high numbers.

**Comment by Accensus** [comment]
Yep. Quite a few.

**Comment by MatthewTheGlutton** [comment]
The Z position is almost 2 million, which I doubt any map has anywhere for any reason.

Even if a revenant ball had escaped the bounds of the map sectors the engine should still perceive a ceiling and bounce/explode accordingly. It does not use a custom ticker for movement the way fireballs or bullets or rockets do.

I have no idea what's going on and this could be a highly unusual GZDoom bouncing projectile bug.

**Comment by Accensus** [comment]
I'd report it, but it's so rare that I doubt I'd encounter it again anytime soon, much less reliably reproduce it.

**Comment by MatthewTheGlutton** [comment]
Was this a particularly large map? Looking at the code I think I can see how this could really be a case of an escaping actor... don't know how it could escape the ceiling impact though

**Comment by MatthewTheGlutton** [comment]
Welp. Converted it to a SlowProjectile. Hopefully that should deal with these edge cases.

Now to stop testing this before I puke...

**Comment by Accensus** [comment]
Not too large. https://doomwiki.org/wiki/MAP12:_The_Slimy_Dens_(Bloodstain)

**Comment by MatthewTheGlutton** [comment]
....that definitely doesn't look like the map I was expecting to give a result like this.

Oh well, the regular-projectile collision is still the only thing I can imagine would be causing this problem anyway, so
