### ISSUE TITLE
Tripwires are broken.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#96]
Can be tested on the range. The tripwire appears for a tic and disappears.

**Comment by MatthewTheGlutton** [comment]
Was it working as of b792bad?

**Comment by MatthewTheGlutton** [comment]
I think I know where the problem is... it's one of those commits from that night but not the one I initially suspected

**Comment by MatthewTheGlutton** [comment]
Hopefully I don't re-introduce the floating-grenade bug I noticed in #84 with this...

**Comment by Accensus** [comment]
Tested with b792badc4f4b345c3dfc10268a7ddf5c8ec40149. Works fine.
Tested with master as well after the fix. Also works fine. Thanks!
