### ISSUE TITLE
Strange inconsistency with encumbrance mult and pocket space.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#97]
1. Set encumbrance mult to 0.75.
2. Go to range.
3. Summon about 40 SMG mags (I tested with those but it doesn't matter).
4. Keep picking them up. Eventually you'll refuse to pick up more despite having like 25% pocket space left.

**Comment by MatthewTheGlutton** [comment]
No idea what's going on. All the math in the relevant code seems to check out.

**Comment by MatthewTheGlutton** [comment]
at 0.75 you can pick up 37 mags
at 1.00 you can pick up 28 mags
37*3=111
28*4=112

I think it's the display that's messed up.

**Comment by MatthewTheGlutton** [comment]
Fixed
