### ISSUE TITLE
Feature Request: Give the player some text feedback on vulcanette repair

### ISSUE THREAD

**Issue by TwelveEyes** [MatthewTheGlutton/HideousDestructor#98]
Some flavor text or something similar would be good, I think, whenever you attempt a repair on the vulc. Something to let the player know a repair attempt improved the condition, or made it worse, or didn't improve or hurt anything. Just sitting there trying to repair the vulcanette with no way to gauge progress is pretty boring, especially when the damage gulf between the different `VULCS_BREAKCHANCE` messages is so huge (40, 110, and 250, respectively).

**Comment by caligari87** [comment]
I imagine this could simply take the form of periodic "oops" messages if the breakchance gets worse, or "nice" messages if if gets better, while the player is holding the repair button. Stuff like

> Wait that's wrong
> A little better
> Oops that doesn't go there
> Wait no
> Hey it fits again
> Back into place...
> Hope that wasn't important

Or something a little more descriptive

> You fit a piece back into place.
> A small bob breaks off and falls on the ground. You can't find it.
> You straighten a bent rod, it seems to work again
> Something grinds worryingly.

...etc. Even better if these were generated from madlibs templates like the Boss rifle cleaning messages.

**Comment by TwelveEyes** [comment]
Yeah, that's exactly what I was thinking of caligari. The repairs could also stand to be just a tad faster, I think. Currently you have to do repairs for 10 or so minutes to make any appreciable dent in lowering the breakchance, Forget about actually getting from one breakchance message state to another, unless you have incredible patience.

**Comment by caligari87** [comment]
I think that part is intentional and I agree with it; the vulc is horrendously complex for field repairs (can you imagine trying to repair anything more complex than an AR-15 without gunsmithing and metalwork tools?). Having the ingame repair option is mostly for consistency, not because it's a good or efficient idea on the battlefield.

**Comment by TwelveEyes** [comment]
Sure, that may be the case, but I'm just talking about a gameplay perspective. The DERP and HERP should also be incredibly difficult, if not impossible, to actually field repair, but getting them back into working order with in-map repairs is substantially easier than it should be. Also the HERP is basically a scaled down vulcanette with an IFF and targeting system bolted on, and is so much easier to repair than the vulcanette.

**Comment by MatthewTheGlutton** [comment]
The rationale for the difference is that the robots are presumed to have had some connections or supports on their chassis shot out and broken in obvious ways, while the Vulc's damage is more long-term degradation that messes with the exact way in which they intersect and move each other.

It's like mending a tear in a jacket versus fixing a zipper that keeps catching the fabric halfway up.

That all aside, yes I do intend on adding some kind of feedback when the number changes...

**Comment by MatthewTheGlutton** [comment]
Addressed in 803d80218724d42f22555661d96b8aad64c69eaa
